### ISSUE TITLE
Travis downloading occasionally fails

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#121]
Recently Travis test occasionally fails when downloading scala packages:

https://travis-ci.org/HazyResearch/deepdive/jobs/29659939#L1423
```
[error] (*:update) sbt.ResolveException: download failed: org.scalatest#scalatest_2.10;2.0.RC2!scalatest_2.10.jar
```

https://travis-ci.org/HazyResearch/deepdive/jobs/29659991#L1252
```
[error] (*:update) sbt.ResolveException: download failed: org.fusesource.scalate#scalate-core_2.10;1.6.1!scalate-core_2.10.jar(bundle)
```

https://travis-ci.org/HazyResearch/deepdive/jobs/28555875
```
[error] (*:update) sbt.ResolveException: download failed: org.scala-lang#scala-compiler;2.10.0!scala-compiler.jar
```

https://travis-ci.org/HazyResearch/deepdive/jobs/28555763#L1422
```
[error] (*:update) sbt.ResolveException: download failed: com.h2database#h2;1.3.166!h2.jar
```

Not sure what happens...

**Comment by netj** [comment]
Seems like it was a temporary TravisCI issue.
