### ISSUE TITLE
factor_graph.pdf has dead link

### ISSUE THREAD

**Issue by adamwgoldberg** [HazyResearch/deepdive#200]
http://deepdive.stanford.edu/assets/factor_graph.pdf links to http://deepdive.stanford.edu/doc/inference_rule_functions.html, which 404s.

**Comment by netj** [comment]
@feiranwang Can you fix the pdf? The right link seems to be http://deepdive.stanford.edu/doc/basics/inference_rule_functions.html with `basics/` in between.

**Comment by feiranwang** [comment]
The link seems to be fixed already. It links to a crappy tutorial I wrote...

**Comment by netj** [comment]
No, please fix the broken link to inference_rule_functions.html in the second page of the pdf.

**Comment by feiranwang** [comment]
ok I see
