### ISSUE TITLE
Improving generic feature lib dependency path features

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#206]
In the ddlib code:

https://github.com/HazyResearch/deepdive/blob/master/ddlib/ddlib/gen_feats.py#L79

Currently the dependency path features are treated as a same feature for all dictionaries. However a dependency path from the mention to `dict X` may have different meaning than a same dependency path to `dict Y`.

I think we should add a `dict_id` here. Does this sound reasonable?

@SenWu @rionda

**Comment by alldefector** [comment]
Now we have treedlib and other stuff...
