### ISSUE TITLE
Generic feature library: are NER O* features generally useless?

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#212]
For most applications I am building, I found a set of particular features generated by the feature library is useless. This type of feature often account for a large portion of the generated features, and they does not help much for my applications. The pattern for these features are:

```python
r".*NER.*\[(O| )+\].*"
```

Which are NER features that contain a sequence of continuous "O"s. e.g. `W_NER_LEFT_[O O O]`, `NER_SEQ_[O O]`.

Should we remove it from the feature library? I understand that it may contain some information (it serves almost as a class prior), but it affects the performance quite a bit.

@SenWu @rionda

**Comment by SenWu** [comment]
I will think about it. Thanks!
Can I ask which materials(research paper or news article) are you using? I agree these features will have a lot of O if you are using research paper.
I recommend you remove these features in your own applications.

**Comment by zifeishan** [comment]
@SenWu Thanks! I am using US patents. They are similar to research papers.

I saw that in the Genomics application, we are replacing the "O"s with lemmas. Is that a common improvement?

**Comment by SenWu** [comment]
Yes. Basically, you can ignore features with high coverage in examples. @zifeishan

**Comment by chrismre** [comment]
I'm not sure I follow this discussion :). Is something in this family of features useful in any application?
