### ISSUE TITLE
Generic feature library: position of mention in sentence?

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#213]
Position of mention in a sentence might be important. It could be bucketized and lengths to both front and end could be informative.

e.g. In sentence "At the same time, the ...", for mention candidate "At", two features can be generated: `dist_to_start=0`, `dist_to_end>5`.

Similar features could be generated for relations.

Does this make sense?

**Comment by alldefector** [comment]
Bucketization or continuous features make total sense.

**Comment by chrismre** [comment]
Let's discuss moving the LSA/PCA and simple CRF-like back into a branch?
don't care where =)
