### ISSUE TITLE
issue with Context.deepdiveHome

### ISSUE THREAD

**Issue by samzhang111** [HazyResearch/deepdive#215]
Hi all,

I am working through the tutorial, and running this inference rule (http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html#inference_rules), fails with this error (cannot find tobinary.py):

http://pastebin.com/5XWLcMGm

It looks like the error comes from scala/org/deepdive/inference/datastore/SQLInferenceDataStore.scala on line 918:
```val cmd = s"python ${Context.deepdiveHome}/util/tobinary.py ${groundingPath} ```

It looks like Context.deepdiveHome is being set to "/home/ec2-user/" instead of "/home/ec2-user/deepdive". In scala/org/deepdive/Context.scala, this happens if the "DEEPDIVE_HOME" environment variable is not found.

But DEEPDIVE_HOME is set:

$ echo $DEEPDIVE_HOME
/home/ec2-user/deepdive

I am running Deepdive from the latest master branch. 
I am also running the inference rule independently as its own task in a pipeline.

```pipeline.pipelines.current: [
    "f_has_spouse_features"
]```

```pipeline.run: "current"```

Thoughts?

Thanks,
Sam

**Comment by feiranwang** [comment]
@zifeishan Do you have any idea on this?

**Comment by samzhang111** [comment]
I figured it out. [tutorial_example/step1-basic/run.sh](https://github.com/HazyResearch/deepdive/blob/master/examples/tutorial_example/step1-basic/run.sh#L14) exports DEEPDIVE_DIR with an extra `../`. It is the right number when you run it from the examples directory, but too many if you copy it to app/spouse.

The [tutorial](http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html#preparation) made it seem like I should make $APP_HOME and $DEEPDIVE_HOME into global environment variables, so I was surprised that they were overwritten.
