### ISSUE TITLE
ChunkingApp sometimes hangs

### ISSUE THREAD

**Issue by adamwgoldberg** [HazyResearch/deepdive#226]
As discussed. :)

**Comment by adamwgoldberg** [comment]
@feiranwang @SenWu

**Comment by chrismre** [comment]
Is this fixed?!

**Comment by feiranwang** [comment]
We discussed this could be an akka issue. I wasn't able to reproduce this issue since we discussed, and looking through travis, this one didn't happen in last two months. 
@adamwgoldberg are you still having this issue?

**Comment by adamwgoldberg** [comment]
I couldn't reproduce this after a couple of attempts, but that doesn't mean it's fixed necessarily. I recall the failure rate was pretty low (1 out of 10 or lower). I'm fine closing the issue if others aren't concerned–if someone else sees it again we at least know the fix.

**Comment by netj** [comment]
Intermittent hanging became more regular after refactoring the tests, and I believe 0bc74f20e9d5fac0a05801b21fbb7a3810ddfcc4 fixes this issue.
