### ISSUE TITLE
Tutorial not compatible with Docker

### ISSUE THREAD

**Issue by adamwgoldberg** [HazyResearch/deepdive#231]
- Rewrite tutorial to incorporate Docker

Minor issues:
- Tutorial step1 (etc.) has incorrect DEEPDIVE_HOME path (check for existing one rather than clobbering what exists in the env already)

**Comment by netj** [comment]
It should be easier to write a Docker-compatible or environment-neutral tutorial after removing many hard coded pathnames from our examples.

**Comment by stephenjbarr** [comment]
I am struggling getting Deep Dive working with docker. In particular, it is not clear how the Postgres container needs to be setup in order to work with Deep Drive. Would it be possible to supply the docker command to bring up the Postgres container and Docker container together. Or, even better, to show a [Docker compose](https://docs.docker.com/compose/) script showing how to launch this together.

**Comment by netj** [comment]
Hi @stephenjbarr, sorry our Docker support became low priority as we moved our focus on making the software work on common environments.  Our installer can now set up any Ubuntu or Debian-based cloud instances ready to run DeepDive with a single command.  I'm not familiar with how Postgres containers are set up or the specific way containers are supposed to communicate, but DeepDive is able to talk to any postgres server configured in `db.url` or `$DEEPDIVE_DB_URL`, so it shouldn't be too hard to have it talk to a Postgres container.  It'd be great if you or someone who uses Docker on a daily basis could contribute docs and fixes.

**Comment by stephenjbarr** [comment]
Hi @netj I will try to spend some time on this next week. I am just getting started with DeepDive in general so I may have a bit of questions to ask along the way. I was able to instlal Deep Dive onto an EC2 image and that seemed to work okay, although the Markov Logic Network examples gave some $DBPORT error that I will need to track down.

Thanks! I'll be in touch.

**Comment by alldefector** [comment]
We have docker for build now (and conda packaging). Let's use https://github.com/HazyResearch/deepdive/issues/467 to track docker for distribution.
