### ISSUE TITLE
Encoding / Decoding PostgreSQL Arrays for tsv_extractor

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#236]
Currently if users want to use arrays as input of TSV extractor, they typically use "array_to_string" to add delimiters. It is also not easy for users to figure out how to dump arrays in outputs of TSV extractors.

We should provide ways in a library (ddlib?) to encode / decode PostgreSQL arrays for TSV extractors. There are some code in some of our applications.

**Comment by netj** [comment]
This will be dramatically simplified in the next release:
* With `from deepdive import *`,
* [`@tsv_extractor` and `@returns` decorators and the argument default values abstracts away the TSV parsing in UDFs](https://github.com/HazyResearch/deepdive/blob/new-spouse-example/examples/spouse/udf/map_person_mention.py#L4-L13) as well as
* [how they're called from DDlog](https://github.com/HazyResearch/deepdive/blob/new-spouse-example/examples/spouse/app.ddlog#L91-L92).
