### ISSUE TITLE
Imply factor function

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#238]
When is it desired to use a "Imply" factor function?

For my application, I want to punish the case where variable `a` is True and `b` is False. I tried `Imply(a, b)` but got the learned weights dramatically large.
I simply change it to `And(a, !b)` which should be the negation of the `Imply` factor, and it works properly (learns a small negative weight).

Anyone got similar experience and could explain this?

**Comment by feiranwang** [comment]
There's a bug in imply function in sampler. I think Ce fixed it. Please check the compiled binary (release/dw_linux) under HazyResearch/sampler.

**Comment by netj** [comment]
@feiranwang Wasn't this also fixed somewhere in sampler?  Could you get that merged with the code for #258 as well as any other sampler related ones, then bring the final binary in?

**Comment by feiranwang** [comment]
Sure. That's what I'm thinking. I'll prepare samplers that include all these fixes for release.
