### ISSUE TITLE
When doing inference,  /root/util/tobinary.py path error

### ISSUE THREAD

**Issue by superChing** [HazyResearch/deepdive#239]
I set up deepdive using  Docker .
I'm running the tutorial walkthrough : "Example Application: A Mention-Level Extraction System" .
And things goes well until the inference stage.
The first error log is :
> 05:13:47 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] INFO python: can't open file '/root/util/tobinary.py': [Errno 2] No such file or directory

and the following is more thorough logs:
> 
...
05:13:46 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] INFO  Converting grounding file format...
05:13:46 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] DEBUG Executing: python /root/util/tobinary.py /root/out/2015-03-02T045835 /root/util/format_converter_linux /root/out/2015-03-02T045835
05:13:47 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] INFO  python: can't open file '/root/util/tobinary.py': [Errno 2] No such file or directory
05:13:47 [profiler] DEBUG ending report_id=inference_grounding
05:13:47 [taskManager] INFO  Completed task_id=inference_grounding with Failure(java.lang.RuntimeException: Converting format failed.)
05:13:47 [taskManager] ERROR task=inference_grounding Failed: java.lang.RuntimeException: Converting format failed.
05:13:47 [taskManager] ERROR Forcing shutdown
05:13:47 [taskManager] ERROR Cancelling task=calibration
05:13:47 [taskManager] ERROR Cancelling task=inference

The path `/root/util/tobinary.py` is wrong but should be `/root/deepdive/util/tobinary.py`.
I see the earlier stage had  the right path when execute scripts in '/root/deepdive/util/', may be there is some bug at path reference.

**Comment by adamwgoldberg** [comment]
This is a known issue: #231

**Comment by netj** [comment]
The path issue here seems to be corrected when #245 was fixed.
