### ISSUE TITLE
PostgresInferenceDataStore.scala Error Fix

### ISSUE THREAD

**Issue by Pede23** [HazyResearch/deepdive#240]
Hey guys, I was stuck on this error that always popped up when I tried to run the spouse and other examples.

13:08:41 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] INFO  Copying inference result weights...
13:08:41 [PostgresInferenceDataStoreComponent$PostgresInferenceDataStore(akka://deepdive)] INFO  psql  -d deepdive_spouse  -U yytcadm  -p 5432  -h localhost  -c "\COPY dd_inference_result_weights(id, weight) FROM '/home2/yytcadm/AustinFolder/deepdive/out/2015-03-02T125249/inference_result.out.weights.text' DELIMITER ' ';"
13:08:41 [Helpers$(akka://deepdive)] INFO  Executing command: "/tmp/copy1762199984072317684.sh" 
13:08:41 [Helpers$(akka://deepdive)] INFO  \copy: parse error at ";"
13:08:41 [taskManager] INFO  Completed task_id=inference with Failure(java.lang.RuntimeException: Failure when executing script: /tmp/copy1762199984072317684.sh)
13:08:41 [profiler] DEBUG ending report_id=inference
13:08:41 [taskManager] ERROR task=inference Failed: java.lang.RuntimeException: Failure when executing script: /tmp/copy1762199984072317684.sh
13:08:41 [taskManager] ERROR Forcing shutdown
13:08:41 [taskManager] ERROR Cancelling task=calibration
./run.sh: line 35: 24719 Killed                  deepdive -c $APP_HOME/application.conf

I came across this stackoverflow issue which really helped me out. 
https://stackoverflow.com/questions/24161864/postgresql-8-4-copy-command-parse-error

So just delete the semicolons on line 35 and 47 of $DEEPDIVE_HOME/src/main/scala/org/deepdive/inference/datastore/PostgresInferenceDataStore.scala, re-make, and that should fix the errors.

Thanks.

**Comment by feiranwang** [comment]
Hi @Pede23, thanks for reporting the issue. It seems we don't have this problem for all the machines we have tested. Maybe using a newer version of PostgreSQL (> 9) can solve this problem.
