### ISSUE TITLE
Different tmp dir for each run

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#242]
Currently, when a deepdive run fails, the intermediate files in the tmp dir are not automatically removed. This is useful for debugging, but when you re-run deepdive without manually removing these tmp files, they are often picked up as inputs which then causes unexpected errors. 

One solution may be to use a different tmp dir for each run, eg. /tmp/RANDOM#/.

**Comment by netj** [comment]
The new `deepdive` command uses a fresh output directory for every run, basically isolating each run's tmp dir from each other. https://github.com/HazyResearch/deepdive/blob/270a74b8ba7b5e1c1bbb0b87af2e4983ae28ecff/shell/deepdive-run
