### ISSUE TITLE
Errors in deepdive installation guide, tutorial, etc

### ISSUE THREAD

**Issue by brahmaneya** [HazyResearch/deepdive#245]
Installation Guide:

export PYTHONPATH=DEEPDIVE_HOME/ddlib:$PYTHONPATH

should be (missing dollar sign before DEEPDIVE_HOME)

export PYTHONPATH=$DEEPDIVE_HOME/ddlib:$PYTHONPATH

Creating a new Application:

deepdive: {
      db.default {

should be (extra colon after deepdive)

deepdive {
      db.default {

Walkthrough:

You can check that the relations have been successfully created with the following command:

should be (missing command)

You can check that the relations have been successfully created with the following command: psql -d deepdive_spouse -c "\d"

psql -d deepdive_spouse -c "select * from has_spouse_features where relation_id = '118238@10_1_118238@10_7'"

should be (incorrect relation_id)

psql -d deepdive_spouse -c "select * from has_spouse_features where relation_id = '118238@10_7-118238@10_1'"

In the holdout part, the tutorial doesn't say whether or not to comment out the existing calibration.holdout_fraction: 0.00 line. (But its commented out in the example run.sh)

In the given example run.sh, there's a line saying 

export DEEPDIVE_HOME=`cd $(dirname $0)/../../../; pwd`

which should be saying

export DEEPDIVE_HOME=`cd $(dirname $0)/../../; pwd`

(since APP_HOME is DEEPDIVE_HOME/app/spouse, we should go only two directories up).

**Comment by chrismre** [comment]
@netj has this been merged?
