### ISSUE TITLE
Inference table does not contain evidence variables

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#258]
In the sampler, the variables are divided into query (without supervision label) and evidence (with supervision label). Currently the sampler does not compute probability for evidence variables. (That's why #vars in the inference table does not equal to #variables in total.)

However In the context of distant supervision, users usually need to know the probability even for evidence variables, because distantly supervised labels are noisy. A workaround is duplicating the evidence variables and make the duplicates query, but it's not very elegant, may have problems in a complex factor graph, and it's currently mentioned nowhere in the docs.

I think the sampler should support computing the probability for evidence variables. It probably should be made default, and developers can specify `sampler_args` to turn it off. If we do not want the change, we should at least make developers more aware of it, and point them the right ways to handle it.

**Comment by netj** [comment]
@feiranwang I thought this was now possible through a sampler option, no?  Maybe I'm confusing with #271?

**Comment by netj** [comment]
It seems sampler's sample_evidence branch has the code: https://github.com/HazyResearch/sampler/commit/b721e65060a50f9d71500c7d2ff118e8d90bfa01#diff-bcc8c161c87b19685947789ac42e9fe9R32 @feiranwang Could you bring the binary here, also documenting the sampler option?

**Comment by feiranwang** [comment]
It's different from #271 as this is for inference results. This feature is added in sample_evidence branch, I'll add it to release.
