### ISSUE TITLE
Docs for using sampler argument -c (data copies)

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#260]
The sampler argument `-c` specifies #numa nodes used for sampling, i.e. data copies. Currently sampler would crash a 1TB memory machine (raiders1) on a 20GB factor graph with 4 data copies (default #data copies matches #NUMA nodes), but it works with 1 data copy. Is there an improvement space?

Some documentation should be given for tuning this parameter, either in the sampler guide, performance guide, or FAQ.

**Comment by feiranwang** [comment]
It's under http://deepdive.stanford.edu/doc/basics/sampler.html

**Comment by netj** [comment]
Did you figure out why the crash was happening?

**Comment by netj** [comment]
The crash seemed to be a hardware issue (raiders1, right @zifeishan?).  The doc about the option could be expanded, but if the default is reasonable discussion about tuning seems unnecessary.  Will close this for now.
