### ISSUE TITLE
docs: little error in /doc/doc/advanced/ubuntu.md

### ISSUE THREAD

**Issue by tiangolo** [HazyResearch/deepdive#261]
In `/doc/doc/advanced/ubuntu.md` it says that it's needed to modify the file `./test.sh` to set the postgre username and password, but those variables are located now in `./test/test_psql.sh`.

I'll submit a pull request with the fix.

Also, if you find it helpful maybe I could create an updated guide for Ubuntu 14.04.

**Comment by netj** [comment]
Taken care by #262.

@tiangolo An updated guide for Ubuntu 14.04 sounds great!  Thanks!
