### ISSUE TITLE
FeatureStats table breaks using array in factor function

### ISSUE THREAD

**Issue by feiranwang** [HazyResearch/deepdive#264]
@raphaelhoffmann and I found this problem. FeatureStats assumes the variables in factor functions are boolean, but they could be boolean arrays, which cause type mismatch.

**Comment by netj** [comment]
Where are we using FeatureStats table?  Unless maintaining this table after every run saves majority of apps time for some set of well-defined frequent tasks, let's drop it from DD and move it to Braindump or Dashboard.

**Comment by feiranwang** [comment]
It's in SQLInferenceRunner. It has been commented out in develop branch. I agree we should drop it and move it to braindump or dashboard. @zifeishan

**Comment by netj** [comment]
I see it's commented out by https://github.com/HazyResearch/deepdive/commit/d1f8449ef990a378cde0e6f763bebd8167f821db#diff-e754f8521322016721729d620efbe663.  @zifeishan Could you create a PR that removes the relevant code if you have no objection?
