### ISSUE TITLE
wrong results when passing array of variables to factor function

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#268]
I'm getting different output when passing variables to a factor function explicitly vs. as array. The results when using array are wrong.

Here's a simple example:
```
deepdive {

  schema.variables {
    candidates.is_true: Boolean
  }

  pipeline.run: debug

  pipeline.pipelines {
    debug = [ create_candidates, one_link_is_true_broken ]
    #debug = [ create_candidates, one_link_is_true_works ]
  }

  extraction.extractors {
    create_candidates: {
        style: sql_extractor
        sql: """DROP TABLE IF EXISTS candidates CASCADE;
                CREATE TABLE candidates (id BIGINT, group_id INTEGER, target INTEGER, is_true BOOLEAN);
                INSERT INTO candidates VALUES (NULL, 0, 0, FALSE);
                INSERT INTO candidates VALUES (NULL, 0, 1, NULL);
               """
    }
  }

  inference.factors {

    one_link_is_true_broken {
      input_query = """
        SELECT array_agg(l.id order by l.id) as "candidates.id", array_agg(l.is_true order by l.id) as "candidates.is_true"
        FROM candidates l
        GROUP BY l.group_id
         """
      function: "And(candidates.is_true)"
      weight: 3
    }

    one_link_is_true_works {
     input_query = """
       SELECT c1.id as "candidates.c1.id", c1.is_true as "candidates c1.is_true",
              c2.id as "candidates.c2.id", c2.is_true as "candidates c2.is_true"
       FROM candidates c1, candidates c2
       WHERE c1.group_id = 0 AND c1.target = 0
       AND c2.group_id = 0 AND c2.target = 1
        """
     function: "And(candidates.c1.is_true, candidates.c2.is_true)"
     weight: 3
    }
  }
```

I'm expecting an expectation of ~0.5 for the unknown variable. When using the array version, the expectation is ~1.0.

**Comment by chrismre** [comment]
@feiranwang @zhangce @netj Take a look please, and let's add in some regression here... :)

**Comment by zhangce** [comment]
@feiranwang can you construct a unit test and check into the sampler repo?
I can fix the code as long as something fails.

Thanks!

Ce

**Comment by feiranwang** [comment]
I'll look into it, and construct a test in deepdive.

**Comment by feiranwang** [comment]
@raphaelhoffmann I tried to run your example, and the sampler gave me the same inference result (0.5). 

However, I do find a bug that results in wrong number of variables for each factor. I'll fix that soon.

**Comment by raphaelhoffmann** [comment]
@feiranwang I noticed that when you use the dw binary included with deepdive, it returns the correct result (0.5). However, when you compile the latest master version of the sampler repo and use that, it will return the wrong result (1.0). Here, I was using clang++ on MacOS for compilation.

**Comment by feiranwang** [comment]
@raphaelhoffmann Sorry I wasn't able to reproduce that on my mac. Maybe try cleaning up before compiling by running make clean?

**Comment by raphaelhoffmann** [comment]
@feiranwang Hmm, just ran make clean and recompiled – same problem. What compiler are you using? 
I ran

    sudo port install clang-3.7
    sudo port select --set clang mp-clang-3.7 
    CXX=/opt/local/bin/clang++ make

**Comment by feiranwang** [comment]
@raphaelhoffmann I am using this `Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)`. I'll check in the fix I mentioned above and see if that is related.

**Comment by raphaelhoffmann** [comment]
@feiranwang Thanks for the hotfix, this example seems to work now. However, some results are still surprising. 

Change the data as follows:
```
    create_candidates: {
        style: sql_extractor
        sql: """DROP TABLE IF EXISTS candidates CASCADE;
                CREATE TABLE candidates (id BIGINT, group_id INTEGER, target INTEGER, is_true BOOLEAN);
                INSERT INTO candidates VALUES (NULL, 1, 0, NULL);
                INSERT INTO candidates VALUES (NULL, 2, 0, NULL);
                INSERT INTO candidates VALUES (NULL, 2, 1, NULL);
                INSERT INTO candidates VALUES (NULL, 3, 0, NULL);
                INSERT INTO candidates VALUES (NULL, 3, 1, NULL);
                INSERT INTO candidates VALUES (NULL, 3, 2, NULL);
                INSERT INTO candidates VALUES (NULL, 4, 0, NULL);
                INSERT INTO candidates VALUES (NULL, 4, 1, NULL);
                INSERT INTO candidates VALUES (NULL, 4, 2, NULL);
                INSERT INTO candidates VALUES (NULL, 4, 3, NULL);
               """
    }
```

Then look at the output:

```
# select * from candidates_is_true_inference order by group_id, target; 
id | group_id | target | is_true | category | expectation
----+----------+--------+---------+----------+-------------
  0 |        1 |      0 |         |        1 |           1
  1 |        2 |      0 |         |        1 |       0.489
  2 |        2 |      1 |         |        1 |       0.956
  3 |        3 |      0 |         |        1 |       0.498
  4 |        3 |      1 |         |        1 |       0.912
  5 |        3 |      2 |         |        1 |       0.918
  6 |        4 |      0 |         |        1 |       0.499
  7 |        4 |      1 |         |        1 |        0.88
  8 |        4 |      2 |         |        1 |       0.884
  9 |        4 |      3 |         |        1 |       0.875
(10 rows)
```

The expectation should be ~1 for all variables.

**Comment by feiranwang** [comment]
I'll check this.

**Comment by chrismre** [comment]
@zhangce @netj Can you take a look at this too? Can we get some regressions?!?! :) We had some... they appear to be broken or not expressive enough... 

Let's just track this down!

**Comment by feiranwang** [comment]
I think I found the problem. I'll add test after fixing this issue.

**Comment by feiranwang** [comment]
@raphaelhoffmann I fixed this in hotfix_array branch. Now the results should make sense. The results should be
```
group 1: P(v = 1) = (e^3)     / (1 + e^3)  = 0.95
group 2: P(v = 1) = (e^3 + 1) / (3 + e^3)  = 0.91
group 3: P(v = 1) = (e^3 + 3) / (7 + e^3)  = 0.85
group 4: P(v = 1) = (e^3 + 7) / (15 + e^3) = 0.77
```

**Comment by chrismre** [comment]
Please make sure that we have regressions for each of the factor #s!

**Comment by raphaelhoffmann** [comment]
It works great now. Thanks, Feiran!

**Comment by chrismre** [comment]
Great! Please make sure a suite of new tests are setup for this :)

**Comment by feiranwang** [comment]
New tests will be merged soon.
