### ISSUE TITLE
Temporary table names should be generated independently

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#276]
In extraction and grounding, DeepDive creates temporary views and tables by extending user's names specified in application.conf.  Most DBMS have length limit, so this can cause problem when names become too long, e.g., #274.  We should fix relevant parts to generate temporary names completely independent from user's input, e.g., `_dd_tmp_1234567` instead of `very_very_very_very_long_user_table_name_unload_very_very_very_very_long_user_function_name`.

**Comment by alldefector** [comment]
We don't have temp tables like the above anymore, though we still have tables like `dd_categories_$usertable`. 14 chars longer isn't a big concern (even though we could shorten it to `dd_cat_`). Either way, as long as the DB consistently panics and gives meaningful error messages, that should enough not to frustrate the user for now.
