### ISSUE TITLE
Restart DeepDive from a "checkpoint"

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#280]
Currently when DeepDive quits during grounding or sampling, we do not have the ability to recover from a near point the next time it runs. The closest thing we can do is restarting the whole grounding, or using "relearn_from" parameter to restart from the grounded factor graph. 

Following features should make recovering easier:

1. If DeepDive quits during grounding, next time it executes it can restart from the query in grounding where it quits.
2. If DeepDive quits anywhere after sampling, it should be able to start from loading the sampler results, instead of rerunning the sampler.

**Comment by chrismre** [comment]
I love this! Please add this to the plans for 0.06.1 release (the maintenance release after DDLog)
