### ISSUE TITLE
high variance in output of sampler

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#282]
We have several reports of high variance in predictions and learned weights between multiple runs (observed by Toshiba, 341 team, and myself).

We want to fully understand what is causing this and how to best deal with it.

**Comment by raphaelhoffmann** [comment]
I did some measurements of variance on the simple spouse example (/deepdive/examples/spouse_example). In each case, I ran 20 iterations of the sampler using the default settings.

I tried both the sampler before April 29th (old) and the sampler after April 29th (new). Zifei also suggested to try switching the symmetry factor (Equal(A,B) with learned weight) on and off. Below are variance of expectations, and variance of learned weights for all combinations:

**new sampler, with symmetry**
```
Average variance expectations  : 0.05173602954174087
Average variance weights       : 2.868037752352032
```

**old sampler, with symmetry**
```
Average variance expectations  : 0.00468157241586358
Average variance weights       : 0.0030183971679320445
```

**new sampler, without symmetry**
```
Average variance expectations  : 0.08879336425759929
Average variance weights       : 0.21628128085863527
```

**old sampler, without symmetry**
```
Average variance expectations  : 0.0011099367678029117
Average variance weights       : 0.0012100521803007904
```

We can conclude
* variance goes up when we add the symmetry factor
* variance goes up when we use the new sampler

**Comment by raphaelhoffmann** [comment]
@feiranwang Here are some numbers on the Chunking Example. This example has 3 factors: 1. logistic regression, 2. linear chain CRF, 3. skip-chain CRF. All weights are learned.

Details below, but the high-level message is that the results are largely consistent with the previous experiment.

(The only surprise is that adding skip-chain CRF factors reduces variance in both cases !?)

**old sampler, 3 factors**
```
Average variance expectations  : 3.478433970813495e-05
Average variance weights       : 0.0013675461712029696
```

**old sampler, 2 factors**
```
Average variance expectations  : 3.2690989117771345e-05
Average variance weights       : 0.0015932013418684728
```

**old sampler, 1 factor**
```
Average variance expectations  : 1.547835036452601e-05
Average variance weights       : 0.0007665820282586536
```

**new sampler, 3 factors**
```
Average variance expectations  : 9.510826048157778e-05
Average variance weights       : 0.003406234197422947
```

**new sampler, 2 factors**
```
Average variance expectations  : 0.00011861153511291191
Average variance weights       : 0.005766963065798057
```

**new sampler, 1 factor**
```
Average variance expectations  : 2.1697729640831944e-05
Average variance weights       : 0.001199654528888731
```

**Comment by zhangce** [comment]
@feiranwang What changes have been done on Apr 29?

@raphaelhoffmann For the spouse example, does the old sampler (the one with lower variance) produces the "same quality" result as the "new sampler"?

Ce

**Comment by feiranwang** [comment]
@zhangce Here is the commit https://github.com/HazyResearch/sampler/commit/ca3e8d45ef1c1c7d8badd16f82eb02847118d744. The change is sampling all variables during learning.

**Comment by zhangce** [comment]
@feiranwang I am confused by this code.

The learning works as follows. There are two set of possible worlds, one contains
all possible worlds that are consistent with the evidence (call it I_e), another are
free to choose values on evidence values (call it I).

The goal of learning is to make sure the expectation of factors matches between I_e and I.

Therefore, we need to draw samples from I_e and I.

     1. if v is evidence, you consider to flip it in I; you do not care I_e because it cannot change in I_e
     2. if v is not evidence, you consider to flip it in I; then you consider to flip it in I_e

Now, in 2, you only flip it in I but not I_e? Is this where the bug sits?

Ce

**Comment by feiranwang** [comment]
@zhangce I think the code follows the above procedure. Case 2 is reflected in https://github.com/HazyResearch/sampler/blob/master/src/app/gibbs/single_thread_sampler.cpp#L50.

If v is not evidence, we flip it in I_e (line 50 - 66), and flip it in I (line 68-77), and update weight.

**Comment by zhangce** [comment]
@feiranwang ah sorry, I understand it now.

How are the weight being initialized now? Random?

Ce

**Comment by feiranwang** [comment]
@zhangce They're all initialized to 0 for unknown weights.

Do you think it makes sense in case 2, we flip the variables, but do not use them to update weights, since they do not give information about the weights? Maybe we can talk in more detail.

**Comment by chrismre** [comment]
This is open in two issues. Closing this one.
