### ISSUE TITLE
Make Test Postgres Issue

### ISSUE THREAD

**Issue by abresler** [HazyResearch/deepdive#294]
When I try running the make test I am getting a password request when there shouldn't be one.  I have tried my passwords for my Postgres servers and those don't work either.  Any idea how to work through this?

**Comment by chrismre** [comment]
@netj @zhangce @feiranwang Can you take a look at this?

**Comment by netj** [comment]
@abresler Could you elaborate on how you installed Postgres?  You need to set `PGUSER` and `PGPASSWORD` environment variables correctly.  You're perhaps trying your password with the wrong `PGUSER` or don't have an account set up in Postgres yet in this case.

**Comment by abresler** [comment]
Brew install postgresql

**Comment by netj** [comment]
Did you set up anything besides running `postgres -D /opt/homebrew/var/postgres`?  Does `psql -l` show you a list of databases?

If standard stuff all fails, you can use `initdb /var/tmp/dd.db` to create a new home for your database and start postgres with `postgres -D /var/tmp/dd.db` where /var/tmp/dd.db can be any path you want to store the data.

**Comment by chrismre** [comment]
did we get any closure on this? I think brew install doesn't automatically createdb appropriately, perhaps we can add a note about this in the docs?

**Comment by abresler** [comment]
Clean reinstalled and got it working sorry about that!  Video or screen
cast on setup could be super helpful though

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by chrismre** [comment]
Makes sense! We are thinking of a few screencasts... we just have to wait
for summer for our day jobs to simmer down!

**Comment by abresler** [comment]
You have no idea how amazing that would be, the wild west of sports data
science is eagerly awaiting, been talking up deepdive because from what
I've been able to tell this could be a game changer in the space.

Keep up the great work everyone.

----------------------
Alex Bresler
abresler@asbcllc.com
​www.asbcllc.com​
917-455-0239​ (cell)​

**Comment by netj** [comment]
Thanks!
