### ISSUE TITLE
PostgresXL Support Docs

### ISSUE THREAD

**Issue by chrismre** [HazyResearch/deepdive#297]
Can we put up some alpha docs about using PostgresXL? Seems like people like it :) @raphaelhoffmann

**Comment by netj** [comment]
@raphaelhoffmann @alldefector Adding a brief introduction page how to use PostgresXL with DeepDive would be awesome for our upcoming release.  Seems like [doc/doc/advanced/postgres-xl.md](https://github.com/HazyResearch/deepdive/new/master/doc/doc/advanced) is a natural place?  It probably doesn't have to be as detailed as [Greenplum's](https://github.com/HazyResearch/deepdive/blob/master/doc/doc/advanced/greenplum.md).

**Comment by raphaelhoffmann** [comment]
Added pull request for PostgresXL documentation #301
