### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#299]
* [x] Bring latest docs from master to develop: f01a4cbf744f5211683e51a1ce8036788b5cbb12
* [x] Forward port any hotfixes in master not applied to develop. 9b1425b37daf9edcb9ef60a45860072dc466791d
* [x] Merge all pending issues and pull requests into develop.
* [x] Add a changelog page.
* [x] Update version number in the website banner image.
* [x] Bump version in build.sbt and Main.scala.
* [x] Merge develop to master.
* [x] Make sure badge URLs are correct, not referring to develop.
* [x] Tag v0.6.0 to master.
* [x] Announce.

**Comment by chrismre** [comment]
Any updates here? :)

We do need a pass on the text of the website too!

**Comment by netj** [comment]
This was pending on one last bug in the sampler's incremental mode with NUMA.  @zhangce and I just decided we can go ahead with the release and follow up with a patch soon.

Yes, the website pass can be done anytime.  Any particular parts you want revision?  The new branching policy we'll use makes it easier as the latest code as well as the website kept in master--currently any change made to website needs to be carefully merged to develop, which is quite annoying around release time.

**Comment by chrismre** [comment]
Ok, that's fine. Why isn't the patch just done? I'd prefer to release all
at once...

Also, can I play with some ddlog examples :)

**Comment by netj** [comment]
It seems the bugfix for HazyResearch/sampler#10 may take a day or two, and the delayed release has been a blocker (mostly mentally) so I wanted to move on to the next things.  However, we can still wait for the patch and mark the release.  Either way is actually fine.

**Comment by chrismre** [comment]
No that's fine. Go ahead with the release, and let's get a list of what's
next!

**Comment by netj** [comment]
Sure.  There's already a rough sketch I made a while ago in the [Milestones tab](https://github.com/HazyResearch/deepdive/milestones), but we can definitely revise this–perhaps splitting into two? 0.7.0 for the cleanups with easy NLP and 0.8.0 for the rest.  More concrete issues can be created to guide individual tasks as I'm already doing for my cleanup.

**Comment by chrismre** [comment]
Sounds good. I would quibble that those should be 0.6.1 and 0.6.2 :)

**Comment by netj** [comment]
I don't like quickly growing version numbers either, but at least I agree with the [Semantic Versioning](http://semver.org) telling us to keep the last number for patching previous releases.  For example, when we patch the known bug in sampler a week later, I think it's simpler to give 0.6.1 to it instead of 0.6.0.1 or so, and use 0.7 for the next milestone.

**Comment by chrismre** [comment]
I would argue that the 0.x is meant to signify we are research software not
ready for release, so just prepend that. :)
