### ISSUE TITLE
Shippable error

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#304]
Shippable checks for every pull request has been marked as failure since a long time ago.  @adamwgoldberg Can we just disable this, or is it anyhow related to shipping Docker containers?  I checked the cause (which was non-trivial, not just a click), and it seems some `gem install` command in our travis.yml needs `sudo`, which isn't necessary for TravisCI.  If Shippable is just running the same tests as Travis, can we get rid of it?  Or will prefixing sudo to the gem command fix everything?

**Comment by netj** [comment]
@adamwgoldberg It seems your shippable-branch contains a working shippable.yml.  However, I'm questioning why we need Shippable in addition to Travis.  Please comment on why we need Shippable if there's a straightforward reason. (maybe in connection to Docker?)

One nice part I see is Shippable gives a good summary on failed tests/assertions in Scala code.  However, if it doesn't provide any real extra value, then I think we should get rid of it to reduce maintenance burden.

**Comment by netj** [comment]
Now, #311 will clear the Shippable error on our side, but tests using `COPY FROM` keeps failing due to their limitation (Shippable/support#1503).

**Comment by adamwgoldberg** [comment]
Right, the original reason was to have performance testing on known hardware. I think that's something we can table for now. I'll remove it now.

**Comment by netj** [comment]
I see.  Perf testing sounds like a compelling reason to keep container-based tests.  But for now, yeah let's turn it off if you can.

**Comment by adamwgoldberg** [comment]
Turned it off. Opened #313 as well.

**Comment by netj** [comment]
Thanks.  Did you just remove repo hooks from GitHub, or something else from Shippable?  It wasn't very clear to me how to turn it off.

**Comment by adamwgoldberg** [comment]
I disabled the project on shippable.com and removed the repo hooks. I
suppose you didn't have access to the shippable login. Whoops. :)

**Comment by netj** [comment]
That explains.  Thanks!
