### ISSUE TITLE
Running DeepDive without learning

### ISSUE THREAD

**Issue by minafarid** [HazyResearch/deepdive#316]
In the `has_spouse` example, I ran the whole pipeline, including learning, inference, etc., and the weights of the features are learnt and stored in `dd_inference_result_weights_mapping`
Is it possible to use the learnt features to classify new `has_spouse` candidate tuples without re-running the inference part? In other words, can DeepDive use the learnt model (features and their weights) to classify unseen examples?

**Comment by chrismre** [comment]
Hi Mina,

Should be! @feiranwang cc: @netj. We're pushing for a release right now, so it may be a small delay until they can respond. We'll get back to you soon! All the best, Chris

**Comment by feiranwang** [comment]
This feature is available in develop branch right row. You can search `skip_learning` in the doc folder. There are some documentation about how to use learned weights to make new predictions. More details will come out soon.

**Comment by minafarid** [comment]
Thank you!
