### ISSUE TITLE
Refactor Scala code

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#329]
1. Remove clutter from Scala
    * [ ] Rewrite calibration plot generator in a separate post-processing script and remove org.deepdive.calibration._
    * [ ] Remove org.deepdive.settings.models._ and have the rest of the code use Config.get* directly as much as possible
    * [x] Rewrite SettingsParser.scala to simply validate and fallback to default values for
        * [x] db.default, schema, calibration, sampler, pipeline
        * [x] every extraction.extractors
        * [x] every inference.factors
        * [ ] except for providing some utilities
    * [ ] Drop json_extractor support

2. Remove Akka by emitting an execution "Plan" instead of immediately executing SQL queries and commands
    * [ ] Add a Plan class to hold SQL queries and arbitrary commands
    * [ ] Add easy ways to emit SQL queries and commands
    * [ ] Add an easy way to group them to create an hierarchy
    * [ ] Add an easy way to declare dependency among them
    * [ ] Rewrite org.deepdive.inference._ and .extraction._
    * [ ] Write a code generator that translates a Plan holding a DAG of SQL/commands into a shell script
    * [ ] Have `deepdive` command first generate the shell script, then execute it

3. Decouple database drivers
    * [ ] Duplicate InferenceRunner implementation for every backend, inlining *Datastore: postgresql, greenplum, postgresql-xl, mysql, mysqlcluster
    * [ ] Duplicate ExtractorRunner for every backend as well

**Comment by chrismre** [comment]
+1
