### ISSUE TITLE
Update/remove performance tuning page

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#337]
https://github.com/HazyResearch/deepdive/blob/master/doc/doc/advanced/performance.md

* [x] Use `deepdive.conf` instead of `application.conf`
* [x] Use the new `deepdive` command instead of `sbt`
* Perhaps `gpfdist` stuff belongs to the [Greenplum page](http://deepdive.stanford.edu/doc/advanced/greenplum.html) and should be removed?
* Then the rest are not so useful, and the whole page may be removed.

**Comment by SenWu** [comment]
Updated the first two tasks.
