### ISSUE TITLE
Newest Version Post Curl Install Test

### ISSUE THREAD

**Issue by abresler** [HazyResearch/deepdive#340]
Team, first off congrats on all the great progress and recent improvements.  Recently cleared and reinstalled the newest push and was wondering if there were new parameters to test the install akin to the old make test.  Also wondering how we can go about re doing the base spouse test or if there was a new tutorial you could point?

Great work, this is a very special project that can change a lot of things in our world, something I hear you guys already experiencing!

**Comment by netj** [comment]
Thanks for your input!

For the moment, there's no test we prepared for the binary installation, but this is an important point we missed, and we'll add an easy way to test very soon.

The [tutorial pages](http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html) have all been revised with the [new, cleaner app structure and command-line interface](http://deepdive.stanford.edu/doc/advanced/deepdiveapp.html).  Please take a fresh look at them. :)
