### ISSUE TITLE
PostgresXL assignID is slow

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#343]
When using PostgresXL, assignID is the bottleneck for grounding. It appears to me to be single-threaded. It should be done in parallel within each segment.

**Comment by zifeishan** [comment]
It turns out I am using a version without XL integration.

**Comment by netj** [comment]
@zifeishan Could you confirm if this is still an issue with the latest and close otherwise?

**Comment by zifeishan** [comment]
Starting from release v0.6.0, the speed is acceptable.
