### ISSUE TITLE
deepdive run doesn't report an error when extractor dependencies are misspelled

### ISSUE THREAD

**Issue by kconor** [HazyResearch/deepdive#349]
It's more or less a silent failure.  The only indication in the logs is order in which the extraction manager executes the extractors.

**Comment by chrismre** [comment]
@netj I thought this was fixed some time back... Also Kevin are you using ddlog? This takes care of building the dependencies for you... @feiranwang is that tutorial up?

**Comment by kconor** [comment]
No, I'm following http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html.

**Comment by netj** [comment]
@chrismre Unfortunately, not yet. You're probably remembering a fix for the pipeline. #329 is supposed to fix all these nasty glitches, but other priorities have been slowing down its progress.  I'll see if I can quickly get some important pieces done first to prevent these issues.

@kconor Sorry, the dependencies config isn't reliable!  For the moment, please specify all extractors in the pipelines config.

**Comment by feiranwang** [comment]
FYI, ddlog tutorial is on http://deepdive.stanford.edu/doc/basics/ddlog.html.
