### ISSUE TITLE
installation instructions don't work on os x

### ISSUE THREAD

**Issue by mcfrank** [HazyResearch/deepdive#352]
So I'm trying to install from the instructions on the installation page on os x 10.10.4. I can install binaries only (option 2), but installing the dependencies throws an error. option 1 (full install) gives:

`## Failed installation for _deepdive_runtime_deps`

without any more verbose errors. From source gives me:

`make: *** No rule to make target `install'.  Stop.`

At first we were thinking there was a permissions issue in getting the dependencies compiled and installed, but now I'm not sure? Initial curl prompt is:

```
Sandra:Projects mcfrank$ bash <(curl -fsSL deepdive.stanford.edu/install)
### DeepDive installer for Mac
++ curl -fsSL https://github.com/HazyResearch/deepdive/raw/v0.7.x/util/install/install.Mac.sh
1) deepdive
2) deepdive_from_release
3) deepdive_from_source
# Select what to install (enter a number or q to quit)? (23) Failed writing body`
```

which includes `(23) Failed writing body` - might result from some issue with text encoding or reading, per [this](http://stackoverflow.com/questions/16703647/why-curl-return-and-error-23-failed-writing-body). But when I move the installer locally and then run I still get the same issue... any help appreciated - thanks!

with @mikabr and @mllewis

**Comment by netj** [comment]
Sorry for the hassle guys.  It turns out we didn't test carefully enough on vanilla OS X.  The installer script should now work as expected now.

**Comment by AliceInTheWonderland** [comment]
I have similar error on macOS Sierra 10.12.5

+ tar xzvf deepdive-v0.8-STABLE-Darwin.tar.gz -C /Users/andyck/local
tar: Error opening archive: Failed to open 'deepdive-v0.8-STABLE-Darwin.tar.gz'
## Failed installation for deepdive_from_release
## Failed installation for deepdive
# Install what (enter to repeat options, a to see all, q to quit, or a number)?
