### ISSUE TITLE
Setting extractor-level parallelism in DDLog?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/deepdive#356]
How can you set the extractor-level parallelism (i.g. the `xargs` parallelism for running each single extractor) in DDLog?

I know that you can (presumably, from `v0.6.x`) go into the compiled `deepdive.conf` file and then add e.g. `parallelism: ${PARALLELISM}` to every extractor, but is there some better way to do this / can there be?

The question of whether we'd want to set this for each individual extractor (as is done pre-DDLog) or just have one global specification is worth asking I think:
* The former offers more flexibility (for ex: what if a certain extractor has large overhead for loading resources, but then is super-fast to run, and so we might want to run it with lower parallelism)
* The latter is much simpler

I'd be very happy with just the latter; either way seems like this should be incorporated somehow (what is the default now btw..?)

**Comment by chrismre** [comment]
I like the default and then override strategy... but Jaeho is the boss.

**Comment by ajratner** [comment]
For reference, in case of use to anyone, a simple solution with sed is
```bash
java -jar ${DEEPDIVE_HOME}/util/ddlog.jar compile app.ddl | sed -e 's/^\(.*\)\(style: "tsv_extractor"\)/\1\2XXNXX\1parallelism: 8/g' -e $'s/XXNXX/\\\n/g' > deepdive.conf
```

**Comment by netj** [comment]
@feiranwang Didn't we solve this from ddlog compiler and deepdive-run at some point by providing a reasonable default parallelism and making this a non-issue?  Could you give a check and close?

**Comment by feiranwang** [comment]
This is done in 0b387b388a2d182e0b4e26f4bff3ba7ee1f74864. Closing.
