### ISSUE TITLE
plpy extractor PATH issue in latest release

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#358]
`$DEEPDIVE_HOME/uti` is not under PATH any more, which breaks the plpy extractor pipeline here:

https://github.com/HazyResearch/deepdive/blame/master/src/main/scala/org/deepdive/extraction/ExtractorRunner.scala#L534

**Comment by netj** [comment]
PATH set up is done by [`deepdive`](https://github.com/HazyResearch/deepdive/blob/master/shell/deepdive#L37-L38) command.  Note that `$DEEPDIVE_HOME` is no longer the root of the source tree to make binary releases possible.  Instead [stage.sh](https://github.com/HazyResearch/deepdive/blob/master/stage.sh#L101) places all scripts under util/ in the directory that becomes `$DEEPDIVE_HOME`.

I think you're not running the scala code through `deepdive env` which takes care of setting up the environment correctly.

**Comment by zifeishan** [comment]
Got it. Thanks!
