### ISSUE TITLE
util/format_converter and util/sampler-dw not found

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#359]
After going through the installation using `bash <(curl -fsSL deepdive.stanford.edu/install)`, I found the following utils missing:
 `util/format_converter` and `util/sampler-dw`.

They don't seem to be extracted into `util/` anymore, which breaks the grounding and inference pipeline. Am I missing anything in installation?

**Comment by netj** [comment]
Did you use the binary release option from the installer?

**Comment by zifeishan** [comment]
I was running an old application, which does not run via `deepdive run`. Thanks!

**Comment by netj** [comment]
I see.  The updated [changelog for 0.7.0](http://deepdive.stanford.edu/doc/changelog/0.7.0-alpha.html) will hopefully prevent others from falling into the same issue!
