### ISSUE TITLE
ddlog column names of views messed up?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/deepdive#360]
I wrote a ddlog program which uses some intermediate statements to serialize data- following Ce's [example](https://github.com/HazyResearch/pdd/blob/master/paleo.ddl)- and it seems to break because of some column name issues.  For example, I have a table:
```
cells(
  table_id    text,
  cell_id     int,
  words       text[],
  type        text,
  attributes  text[],
  xpos        int,
  xspan       int,
  ypos        int,
  yspan       int
).
```
and then I create the view `cells_serialized` from it:
```
cells_serialized(
  table_id,
  cell_id,
  ARRAY_TO_STRING(words, "|^|"),
  type,
  ARRAY_TO_STRING(attributes, "|^|"),
  xpos,
  xspan,
  ypos,
  yspan
) :- cells(table_id, cell_id, words, type, attributes, xpos, xspan, ypos, yspan).
```
in order to create the view `tables_serialized`:
```
tables_serialized(
  table_id,
  ARRAY_TO_STRING(ARRAY_AGG(cell_id), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(words), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(type), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(attributes), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(xpos), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(xspan), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(ypos), "|~|"),
  ARRAY_TO_STRING(ARRAY_AGG(yspan), "|~|")
) :- cells_serialized(table_id, cell_id, words, type, attributes, xpos, xspan, ypos, yspan).
```
When I try to run this (or same for any other operation referencing `cells_serialized`) it looks for a column `r0.table_id` from `cells_serialized`, but the column is created with name `R0.cells.table_id`, so it throws a column not found error

I tried to follow Ce's example, am confused- is there something minor I'm messing up?

Thanks!

See [my file](https://github.com/ajratner/truc/blob/master/app.ddl)

**Comment by chrismre** [comment]
@feiranwang @netj this is a ddlog issue?

**Comment by ajratner** [comment]
Sorry, for future reference should I have put this somewhere else?

**Comment by chrismre** [comment]
here is fine :) I'm just interested in DDlog issues right now. Make sure you send notes to those involved.

**Comment by feiranwang** [comment]
Sorry I think ddlog does not support views right now, it has a problem when accessing columns of a view (In Ce's example, he uses views as input to functions, but not accessing individual columns). For a temporary fix, you can define the schema, and then use it. I'll fix this soon.

Let me know if you have any further issues. Maybe under ddlog repo and ping me directly :)

**Comment by ajratner** [comment]
Okay cool

To clarify, for me this is not a big issue- for now I just changed the column names in `deepdive.conf` manually and is working fine

Good point on Ce's example too- that is another easy way for me to temp fix.  So no rush from my end.  Thanks!

**Comment by ajratner** [comment]
Closing- moving ddlog issues to ddlog repo.  Not yet re-opening this one there though, because from my end, defining these intermediate tables in the schema as you suggested- e.g. using separate tables rather than views- is a fine enough solution for now
