### ISSUE TITLE
PGXL failing on large datasets

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#378]
Trying to run one of our memex extractors, PGXL fails on the following query:

SELECT DISTINCT t0.id AS factor_id, t1.id AS weight_id,  "ismassageparlorad.id"
  FROM dd_query_f_ismassageparlorad_features t0, dd_weights_f_ismassageparlorad_features t1
  WHERE  t0."ismassageparlorad.feature" = t1."ismassageparlorad.feature"

A few observations:
- It seems DISTINCT is redundant and can be dropped (?)
- I added an index on the two feature columns, but that didn't help
- feature is not a distribution column – we can try to redistribute the table (but shouldn't that happen automatically, when trying to join?)

**Comment by alldefector** [comment]
PGXL distributes by first usable (primitive types) column by default. If both base tables were distributed by the ID column, this join would probably make each data node send data to all other data nodes -- by the same token, each node would also process data from all other nodes. And the cross-node data pipes might not be very efficiently implemented.

Ideally the DDL code generated by DD should specify the best dist key (by feature in this case).

**Comment by raphaelhoffmann** [comment]
dd_query_f_ismassageparlorad_features (38GB) is distributed by "ismassageparlorad.id".
dd_weights_f_ismassageparlorad_features (18MB!) is distributed by REPLICATION.

This join should be trivial, no matter how the first table is distributed.

We also can't re-distribute the table for every join, because re-distribution is very expensive. I'm currently re-distributing the first table by feature, but the process is CPU-bound with only the coordinator showing activity (100% CPU).

Maybe I'm using too many nodes (32).

**Comment by raphaelhoffmann** [comment]
I tried re-running the query after redistributing the first table.

It's running now on our Azure instance using PGXL at a rate of 3.8MB/sec (this doesn't include the time for redistribution which itself took maybe an hour or more).

I also checked my logs to see how a corresponding query executed on Greenplum on raiders4. There, the rate is 1.8MB/sec (but we don't do redistribution). 

Not sure why this takes so long using either database system. The data is so small that it could easily fit in memory.  

alldefector – when you get a chance can you log into the machine and see if there's an easy fix? Thanks.

**Comment by raphaelhoffmann** [comment]
Here are the query plans:

Greenplum (after ANALYZE):
```
 Gather Motion 48:1  (slice2; segments: 48)  (cost=106201580.45..115136401.10 rows=11701014 width=24)
   ->  HashAggregate  (cost=106201580.45..115136401.10 rows=11701014 width=24)
         Group By: t0.id, t1.id, t0."rates.id"
         ->  Hash Join  (cost=13119111.20..98670881.40 rows=11701014 width=24)
               Hash Cond: t0.feature = t1.feature
               ->  Seq Scan on dd_query_rates_features t0  (cost=0.00..7913286.40 rows=11701014 width=39)
               ->  Hash  (cost=5525981.00..5525981.00 rows=10945052 width=37)
                     ->  Broadcast Motion 48:48  (slice1; segments: 48)  (cost=0.00..5525981.00 rows=10945052 width=37)
                           ->  Seq Scan on dd_weights_rates_features t1  (cost=0.00..162905.52 rows=228022 width=37)
```

PGXL (after redistribution and ANALYZE):
```
 Unique  (cost=300927152.97..315138286.41 rows=1421113344 width=24)
   ->  Remote Subquery Scan on all (data1,data10,data11,data12,data13,data14,data15,data16,data17,data18,data19,data2,data20,data21,data22,data23,data24,data25,data26,data27,data28,data29,data3,data30,data31,data32,data4,data5,data6,data7,data8,data9)  (cost=300927152.97..304479936.33 rows=1421113344 width=24)
         ->  Unique  (cost=300927152.97..304479936.33 rows=1421113344 width=24)
               ->  Sort  (cost=300927152.97..304479936.33 rows=1421113344 width=24)
                     Sort Key: t0.id, t1.id, t0."ismassageparlorad.id"
                     ->  Hash Join  (cost=9161.86..55742915.54 rows=1421113344 width=24)
                           Hash Cond: (t0."ismassageparlorad.feature" = t1."ismassageparlorad.feature")
                           ->  Seq Scan on dd_query_f_ismassageparlorad_features_x t0  (cost=0.00..23758703.44 rows=1421113344 width=22)
                           ->  Hash  (cost=6040.27..6040.27 rows=249727 width=70)
                                 ->  Seq Scan on dd_weights_f_ismassageparlorad_features t1  (cost=0.00..6040.27 rows=249727 width=70)
```

(The unique is unnecessary and it is dropped if you remove DISTINCT from the query; when executing, I ran without DISTINCT.)

**Comment by raphaelhoffmann** [comment]
@SenWu Is DISTINCT necessary for this query?

**Comment by SenWu** [comment]
@raphaelhoffmann I think you can delete it.
