### ISSUE TITLE
PGXL fails on re-using weight table

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#385]
We are currently using a distributed UPDATE query here:

https://github.com/HazyResearch/deepdive/blob/1573cb703079b10cb2dcc93b3d67e09d079d628c/src/main/scala/org/deepdive/inference/SQLInferenceRunner.scala#L871

This is not supported by PGXL: http://sourceforge.net/p/postgres-xl/mailman/message/34113261/ and the following error is returned:

```
ERROR: could not plan this distributed update
```

There are two possible workarounds (see link):
1. Using WITH x AS (...) ...
2. Setting distribution mode of last weight table to REPLICATION.

Not sure which approach is better; the second one works fine. Maybe we should add documentation somewhere?

**Comment by raphaelhoffmann** [comment]
There's another problem with re-using a weight table: The same query is quite slow when the weight table is large (which is the case for all our HT extractors). However, after adding an index on the feature column, it is running quite well.

I suggest we also update the documentation, recommending an index on the feature column when re-using a weight table.

**Comment by netj** [comment]
Closing since weight reuse has been overhauled.
