### ISSUE TITLE
Sequence assignment for variables requires copying of candidate tables 

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#387]
Since sequence assignment creates a copy of a (possibly large) table, it can be slow (i.e. hours). See #379 for details. DeepDive requires sequence IDs for variables.

**Comment by netj** [comment]
I think this is no longer the case for 0.8 but can you confirm @raphaelhoffmann?  I'm not sure what was being copied.  What "copy" were you referring to? materializing the categorical variables or also Booleans? or something done inside the stored procedures?

**Comment by alldefector** [comment]
The UPDATE query for assignment would effectively copy all tuples being updated. I believe that's what @raphaelhoffmann meant... Looks like var ID assignment was thrown out a couple of months ago, so this should have been addressed...

**Comment by netj** [comment]
Sequence assignment has been overhauled and this issue is probably no longer applicable.
