### ISSUE TITLE
Easiest Way Custom Annotations

### ISSUE THREAD

**Issue by vsoch** [HazyResearch/deepdive#388]
I want to use [RegexNER](http://nlp.stanford.edu/software/regexner/) to define a list of custom words (brain regions and cognitive concepts) that will be tagged as either REGION or CONCEPT.

As an example, the top of my `cognitiveatlas-annotations.txt` file looks like this:

      abductive reasoning	CONCEPT
      absolute threshold	CONCEPT
      abstract analogy	CONCEPT

The example on the site to call the extractor is like this:

      java -mx1g -cp '*' edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators 'tokenize,ssplit,pos,lemma,ner,regexner' -file JuliaGillard.txt -regexner.mapping jg-regexner.txt

Where `jg-regexner.txt` would be replaced with `cognitiveatlas-annotations.txt`. Looking at how the extractor is run from deep dive, it's this command in `deepdive.conf`:

           udf             : "examples/nlp_extractor/run.sh -k article_id -v text -l 100 -t 4"
 
and the run script seems to export some environmental variables for sbt:

      #! /usr/bin/env bash
      export SBT_OPTS="-Xmx1g"
      $(dirname $0)/target/start $@

and the start script sets the project directory and main class:

      #!/bin/bash
      PROJECT_DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd -P)/..
      MAINCLASS=org.deepdive.udf.nlp.Main

My question is: what is the easiest way to integrate my annotations into the pipeline? Is it just as easy as adding the `-regexner.mapping` argument to the SBT_OPTS variable? It would be most ideal to have a solution that stored with my project (external to the deepdive installation). I noticed [this PR](https://github.com/HazyResearch/deepdive/pull/250) that seems to be about adding custom annotations, but the comment seems to be about running things in parallel so I'm not sure if it's relevant. My first thought was just to integrate discovering the concepts in an extractor, but it seems highly inefficient to loop over every word, and every concept or brain region, and check for matches (is that what people sometimes do?). 

I think what I want to do is pretty simple - it's really just specifying regular expressions to get specific NER tags, otherwise the extractor isn't so useful to help find the brain regions and concepts. If it were run in parallel this might not be such a nutty idea, but I haven't even found the documentation for that yet. Any pointers to relevant documentation or tips would be greatly appreciated! The database I'm working with has to be recompiled for nlp_extractor to work and it isn't happening until the 15th, so there is no time urgency. Thanks!

**Comment by chrismre** [comment]
@netj and @ajratner  is thinking about how to make this process dramatically easier... I don't know what the current status is :)

**Comment by vsoch** [comment]
Is there a branch I could look at for inspiration? Even just a push in the right direction I think I could get something working for our analysis.

**Comment by chrismre** [comment]
adding more people I emailed :) @thodrek @feiranwang

**Comment by vsoch** [comment]
I think I found a lot of examples [here](https://github.com/rionda/dd-genomics) that will be good to get me started!

**Comment by chrismre** [comment]
I'm not sure how good those examples actually are... @netj when you get back online can you sync up?

**Comment by netj** [comment]
Hi @vsoch, it's possible to do the tagging with RegexNER while running CoreNLP, but in typical DeepDive apps it's done as you first thought by writing extractors that scan every word/phrase.  That's partly because your tagging (or candidate mapping) extractor evolves a lot while most of the compute heavy NLP don't, so decoupling speeds up the development.  We're currently working on an easier way to construct efficient extractors that rely on dictionaries or set of patterns, but until we have something readily usable, I think it's fine to get started with a naive version and optimize as needed.  [PaleoDD](https://github.com/zhangce/pdd) may be a good example to look at.

**Comment by vsoch** [comment]
Thanks for the feedback, and the example! That strategy is very logical, I agree that the candidate mapping is likely to evolve, and actually it's the extractors that seem like they would be the most variable out of all things in the application. I will move forward with enveloping the regular expressions there.

**Comment by naddou14** [comment]
Hello,

First of all, I want to say thank you to every person who participated in DeepDive's development. It is really great!! 
Second, I want to know if there is any news about custom annotations? If not, can you please make the approach that @netj has proposed more clear? 

Thank you for answering.
Nadia
