### ISSUE TITLE
Set field names for JSON extractor depending on the ddlog function definition attributes

### ISSUE THREAD

**Issue by AlexisBRENON** [HazyResearch/deepdive#389]
Hi,

In DDLog, I define a function and call it this way :

    function ext_eating_candidates
      over (sample_id bigint, activity text, activity_to_cast text)
      returns (sample_id bigint, is_true boolean)
      implementation "udf/cast_activity_to_bool.py"
      handles json lines.

    eating_candidates +=
      ext_eating_candidates(sample_id, activity, "eat") :-
        samples(sample_id,_,_,_,_,_,_,activity).

Nevertheless, in the Python extractor field names are :
* samples.R0.sample_id
* samples.R0.activity
* column_2

It could be easier for the extractor developer if the field names would be the same as the ones used in function declaration, i.e.:
* sample_id
* activity
* activity_to_cast

If the function is defined with a `over rows like` structure, using the same name as the table attributes could be great too.

Kind Regards,
Alexis BRENON

**Comment by netj** [comment]
Thanks for pointing out! These are rough corners that were overlooked for json. @feiranwang could you take a look?

**Comment by feiranwang** [comment]
I'll look into this. Btw, the recommended extractor type is tsv extractor, which is much faster than the json extractor. In tsv extractors, columns names are irrelevant, while the order does.

**Comment by AlexisBRENON** [comment]
Even if it's faster, I think that JSON extractor, based on column name and so, that gives some semantic to your extractor, is far better for maintenance: in case you have to add or remove some attributes, you can easily check its existence with JSON, but not with TSV. Both are useful, depending on your goal : speed or continued existence.

**Comment by chrismre** [comment]
This is a great point, and we do support both for that reason. Speed issues
to one side, we'd prefer a nice human reasable format. However, I think
what Feiran's saying is that the speed penalty for JSON can be
unreasonable. We've had people stub their toes on building JSON extractors,
only to find out it doesn't scale later. You're more than welcome to use
it!

**Comment by netj** [comment]
This becomes less of an issue with #565 and the `@tsv/tsj_extractor` decorators.  I agree ddlog function calls can be improved to alias the input columns per its declaration.  However, since we dropped support for json_extractor, which is the only one where the column names matter, I'm closing this issue.
