### ISSUE TITLE
deepdive: command not found

### ISSUE THREAD

**Issue by ukliu** [HazyResearch/deepdive#401]
Hi, it's me again. As a beginner in both deepdive and SQL, I might keep asking level-0 questions here. Sorry to keep bugging you @netj .

I was running the Tutorial on deepdive website "http://deepdive.stanford.edu/doc/basics/walkthrough/walkthrough.html". And got stuck at the stage "Database Configuration", step 'deepdive initdb'. Each time I typed this, there is an error message, "-bash: deepdive: command not found". Does that mean deepdive is not correctly installed on my computer? I checked the app/spouse folder, deepdive.conf is there.

BTW, the app/spouse folder contains three files, db.url, deepdive.conf, schema.sql. Is there some file missing?

Thanks in advance!

**Comment by netj** [comment]
@ukliu I'm sorry for not responding earlier to this simple issue. You probably forgot to add the directory where `deepdive` is installed to the `PATH` environment (3rd step of [Quick Installation](http://deepdive.stanford.edu/doc/basics/installation.html)).  Open a new terminal if you already modified `~/.bash_profile`.

**Comment by ukliu** [comment]
@netj Thanks a lot, it works! I did that step in the original installation, but did not do it when everything was reinstalled last night. 
I might keep bothering you in the future.  Thank you for your patience and help, I really appreciate them.

**Comment by netj** [comment]
@ukliu My pleasure!
