### ISSUE TITLE
DDLog execution of plpy extractors fails on PGXL because of incomplete view support in PGXL

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#403]
Error:
00:20:52 [Helpers$(akka://deepdive)] INFO  ERROR:  column "doc_id" does not exist
00:20:52 [Helpers$(akka://deepdive)] INFO  LINE 3: FROM (SELECT func_extraction_rule_5(doc_id, __words, __sent_...

SQL:
DROP VIEW IF EXISTS dd_tmp_view_func_extraction_rule_5 CASCADE;
CREATE VIEW dd_tmp_view_func_extraction_rule_5 AS SELECT R0.doc_id AS "sentences.R0.doc_id", ARRAY_TO_STRING(ARRAY_AGG(ARRAY_TO_STRING(R0.words, ' ')), '~@#@~') AS column_1, ARRAY_TO_STRING(ARRAY_AGG(R0.sent_id), '~@#@~') AS column_2 FROM sentences R0 GROUP BY R0.doc_id;
INSERT INTO doc(doc_id, text)
SELECT (__X.__COLUMN).doc_id, (__X.__COLUMN).text
FROM (SELECT func_extraction_rule_5(doc_id, __words, __sent_ids) AS __COLUMN
 FROM dd_tmp_view_func_extraction_rule_5) as __X;

Speculation:
PGXL supports CREATE VIEW but the view is not propagated to the data nodes. As a result, if a subplan executed on a data node tries to reference the view, the query fails. Which seems to be what happened above.

Is it easy to inline the view?

**Comment by alldefector** [comment]
OK, looks like it's specific to plpy extractors:
https://github.com/HazyResearch/deepdive/blob/e8b9dc329102c53bb273455953e8ac67a62e579c/src/main/scala/org/deepdive/extraction/ExtractorRunner.scala#L553
https://github.com/HazyResearch/deepdive/blob/master/util/ddext_input_sql_translator.py#L103

If we avoid using plpy extractors, looks like DDLog works on PGXL.

Time to deprecate plpy extractors?

**Comment by chrismre** [comment]
I'm not so sure... they should be *much* faster... can we make sure it
doesn't blow up in our faces?

**Comment by netj** [comment]
plpy extractor support is gone in 0.8 in favor of tsv extractor
