### ISSUE TITLE
Open data provenance columns are malformed

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#405]
The provenance columns in TSV of most [open datasets](http://deepdive.stanford.edu/doc/opendata/) seem to be incorrect and some of them are malformed causing syntax errors when loading into the database.  The CoNLL format seems to contain the correct START/END offsets, so this seems to be a bug in conversion to TSV.
```
$ deepdive sql "COPY sentences FROM STDIN" <./input/bmc_full_dddb/sentences-0.tsv
ERROR:  malformed array literal: "{,/,2/,2/,1/,6/,7/1,24/1,26/1,28/1,43/1,51/1,60/1,64/1,69/1,76/2,07/2,86/2}"
DETAIL:  Unexpected "," character.
CONTEXT:  COPY sentences, line 1, column bounding_boxes: "{,/,2/,2/,1/,6/,7/1,24/1,26/1,28/1,43/1,51/1,60/1,64/1,69/1,76/2,07/2,86/2}"
```

**Comment by zhangce** [comment]
@netj The fixed run started, ETA tomorrow afternoon for all datasets. Sorry for the bug here.
