### ISSUE TITLE
Open data READMEs are out of sync and need more description

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#406]
* [ ] The TSV formats contain lemma columns but they do not appear in the README.
* [ ] Some people were asking for a one-sentence description of each column.
* [ ] Adding hints for creating indexes over which columns for speeding up DeepDive to the README would be useful.

**Comment by zhangce** [comment]
@netj Maybe these three should happen in the walkthrough? When I 
describe the data format in the open data page, I pointed it to the 
walkthrough...

**Comment by thodrek** [comment]
@netj @zhangce I'll do a pass over the documentation as well. Starting now.

**Comment by zhangce** [comment]
@thodrek Sorry for the confusion, just to be clear, the open data doc is not the core part--you can focus on the main doc (I can deal with everything related to open data `opendata/index.md`)

**Comment by netj** [comment]
@zhangce Yes, perhaps adding in the README a link to the right section of the tutorial or even to the opendata page is enough.  Once people download these datasets, they seem to get detached from the web page and expect things to be self-contained.

**Comment by zhangce** [comment]
I see, I will make it clear in the README where to look up. Thanks!

Ce
