### ISSUE TITLE
Can not learn static weight from inference rules.

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#408]
My inference rule:
      input_query: """
        SELECT is_product.id AS "is_product.id",
               is_product.is_true,
               is_keyword_here.ids AS "is_keyword_here.id",
               is_keyword_here.keyword_product,
               is_keyword_here.not_keyword_product
        FROM is_product,
             is_keyword_here
        WHERE is_product.relation_id = is_keyword_here.relation_id
      """

      # Factor function:
      function: "Imply(is_keyword_here.key_word_product,is_product.is_true)"

      weight: 10
But  my result:
![is_product is_true](https://cloud.githubusercontent.com/assets/9162294/10094476/86f761d2-638a-11e5-9a0c-b8d83536ce3f.png)

And "is_keyword_here.key_word_product" column and "is_product.is_true" column are Boolean type.
All of is_keyword_here.key_word_product" column values is not NULL.
So why i don`t have any positive result??(weight =10)??

**Comment by astrung** [comment]
well,anyone can explain for me about this result???

**Comment by netj** [comment]
Is `is_keyword_here.key_word_product` declared as a deepdive.schema.variables?  The histogram centered in the middle tells that DeepDive was not able to learn anything usually due to an empty training set.

**Comment by netj** [comment]
Closing this for lack of response. Please reopen with details if needed. Thanks!
