### ISSUE TITLE
Questions from a beginner

### ISSUE THREAD

**Issue by ukliu** [HazyResearch/deepdive#409]
First of all, thanks @netj  for helping me with the deepdive installation and the tutorial walk-through.  It took me a long time to go through all the tutorial programs line by line and understand how they work.

I have one small question on the tutorial programs, on 
https://github.com/HazyResearch/deepdive/blob/master/examples/tutorial_example/step1-basic/deepdive.conf
line 27,32: Does not “sentences” need to be defined?
I found “sentences_dump.csv” and “sentences_dump_large.csv” in the folder /spouse/input. There is no file names as ‘sentences.tsv”. I am wondering, does the tsv-extractor take those two cvs files as ‘sentences’?

In addition, I have some general questions with the deepdive.

My goal of learning deepdive is to use it to extract and analyze relations out of scientific pdfs (or database containing pdfs). I am from a background of geology, familiar with Python, with some experience of Apache Spark, limited (only know the basic operations such as select, join, etc) experience with SQL, and no experience with Java. For me to master the deepdive, I believe that I have to learn to write the programs similar to what are shown in the tutorial material. My first question is, are there some toy problems similar to the tutorial walk-through used to train newbies? 
Another question is, I used the Mac terminal to run the tutorial programs, which might be perfect for program developers but not friendly enough to me and probably to future deepdive users. Is there a software with GUI that can perform deepdive operations? Do you guys use Java to debug your deepdive programs? 
A third question is, I learned from the website that @zhangce  has developed a geodeepdive DEMO but could not find any website/software devoted to that. Is it still under development or the software has been released privately? Can I use it to perform my task, e.g., extract elemental, mineral and geochronological relations from geological pdf articles/ databases? How do you guys extract relations from pdfs?

Thanks for your patience!

**Comment by chrismre** [comment]
I just want to say--we should definitely be able to get you setup! There
are (ridiculous in my view) restrictions on some of the data from
GeoDeepDive... however, we can set you up with those tasks.

Your background is exactly the type of person we *want* to enable. I'd
propose a deal: we can help you get setup (we'd do this anyway :) ), but
perhaps you can help us document how to make it easier to use and write the
next version.

I'd also say if you can stick to open source information (CC data), we can
put your data our there and get even more users to help you in your goal.

This is very exciting for us!

All the best, Chris

**Comment by zhangce** [comment]
>> A third question is, I learned from the website that @zhangce has developed a geodeepdive DEMO but could not find any website/software devoted to that. 

@ukliu In terms of your third question, you can find the code for PaleoDeepDive at https://github.com/HazyResearch/pdd . You can follow a similar structure for your
application. If you want more simple examples (and because you are from Shanan's team), 
Julia also has an application that she builds from scratch over the summer using DeepDive
that is potentially more easier to follow; but you probably need to ask Shanan for the program.
If you have any Geo-related, Paleo-related, or PDF-acquisition-related questions, we can
discuss via email (and I will point you to the right people to ask).

Thanks!

Ce

**Comment by chrismre** [comment]
Why not give out the ddlog version? it's easier to use right? and it's the
preferred way...

**Comment by zhangce** [comment]
>> Why not give out the ddlog version? it's easier to use right? and it's the
preferred way...

Yes, ddlog is the preferred way to write applications now. The code in 
https://github.com/HazyResearch/pdd is already in ddlog.

**Comment by chrismre** [comment]
I should have checked =)

**Comment by ukliu** [comment]
Thanks for the reply! I cannot open https://github.com/HazyResearch/pdd though.

**Comment by zhangce** [comment]
@ukliu Sorry, just added you.

**Comment by ukliu** [comment]
@zhangce Thanks a lot! Also I sent an email to say hi and introduce myself. Thanks!

**Comment by ukliu** [comment]
@chrismre Dear Chris, thanks for the reply and all your help. I meant to reply it sooner. I am afraid I will keep asking silly questions to learn deepdive. I do not know how many people are trying to learn it, but if there are a lot, maybe it is worth setting up an online course.

**Comment by nhantranfractal** [comment]
Dear Chris and Ce,

I try to open https://github.com/HazyResearch/pdd but the link is not working. Could you please add me so I can download it?

Thank you!
