### ISSUE TITLE
Superuser required for nlp_extractor?

### ISSUE THREAD

**Issue by vsoch** [HazyResearch/deepdive#410]
Is superuser required for use of the nlp_extractor? Earlier in the week we had the correct languages installed in the database (plpythonu) and I am getting permissions errors, and thinking that there is some issue with me not being a superuser. (My colleague at TACC noted that the appendage of "u" on the language means that it is "untrusted."

First, we can talk about the error, it looks like here it is checking that the language exists:

      16:48:14.279 [default-dispatcher-2][PostgresDataStore(akka://deepdive)][PostgresDataStore] DEBUG Executing SQL with callback... SELECT EXISTS (
       SELECT 1
       FROM   pg_language
        WHERE  lanname = 'plpythonu');
        16:48:14.284 [default-dispatcher-2][PostgresDataStore(akka://deepdive)]

here it looks like it's testing a query (with a like statement, which makes sense)

           [PostgresDataStore] DEBUG Executing SQL with callback... SELECT version() LIKE '%Postgres-XL%';
           16:48:14.304 [default-dispatcher-2][PostgresDataStore(akka://deepdive)]

A quick note - is there a reason that the version is checking for %Postgres-XL% when my database URL is postgres:// (and thus should not be postgresql-xl). Here is the permission error:

      [PostgresDataStore] ERROR org.postgresql.util.PSQLException: ERROR: permission denied for language plpythonu
      16:48:14.319 [default-dispatcher-4][extractionManager][OneForOneStrategy] ERROR ERROR: permission denied for language plpythonu

### Debugging
I'm trying to help debug this with the guys at TACC,and here is what we have so far.

#### Superuser

>> Do I need to be superuser to run nlp_extractor?

That would be a quick answer, if this is the case. If it's the case, I'll also need to figure out how to make a pipeline that doesn't require the parser. If the parser is just used for the NERs, I think I could get by without them. I haven't used them thus far (if you remember, it would have been useful to make CONCEPT tags [here](https://github.com/HazyResearch/deepdive/issues/388) but we decided to just write everything into the extractors themselves.

#### Database Type

>> Is the wrong database being specified?

For the database type, it looks like deepdive has drivers for both postgresql and postgresql-xl in [this folder](https://github.com/HazyResearch/deepdive/tree/master/shell). The driver used is determined by parsing the URL that I provide, so for example when I start the URL with "postgresql://" it will select that driver and not the "xl" version:

- the database type variable is [extracted here](https://github.com/HazyResearch/deepdive/blob/master/shell/parse-url.sh#L8)
- and used to determine the [correct folder here](https://github.com/HazyResearch/deepdive/blob/master/shell/load-db-driver.sh#L22)

So based on that, given that it's working as it should, that wouldn't be the issue. I'm still worried about the mention of "xl" in the previous command.

#### Digging for a command

>> Is it something about the command being run?

Here I tried tracing to find the underlying command, and my stopping point was the scala code, for which I'm about as useful as a tropical lizard in the Antarctic. My instinct is that the error has to do with some function from within the nlp_extractor making some regex call to the database, and the call from this function is requiring some level of permissions that it doesn't have.

- We start with the deepdive config, which has defined pipelines to run. I have an "nlp_extract" pipeline to read sentences from one table, run them through the nlp_extractor (where the error seems to be happening), and then write them back to the database. [Here is the exact line to run that](https://github.com/vsoch/neurosynth-nlp/blob/master/deepdive.conf#L19).
- The run script essentially calls another script, "start" and this is compiled by me. I don't want to share the full start code because it reveals paths on TACC, but it basically sends a bunch of libraries to a main class, "org.deepdive.udf.nlp.Main"

      PROJECT_DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd -P)/..
      MAINCLASS=org.deepdive.udf.nlp.Main
      exec java $JAVA_OPTS -cp "$PROJECT_DIR/target/scala-2.10/classes:
          --- bloo bloo bloo
      l-0.23.jar" "$MAINCLASS" "$@"

- I don't know scala, [but it looks like that might be this](https://github.com/HazyResearch/deepdive/blob/master/examples/nlp_extractor/src/main/scala/Main.scala)? 

At this point I think the HazyResearch's group expertise would be helpful, since you guys are more like penguins in the Antarctic when it comes to scala and the parser! Could we chat about some of the points above (and teach me how to be a penguin? :penguin: :smile: ) Thanks!

**Comment by alldefector** [comment]
Yes, it appears plpythonu does require super user: http://stackoverflow.com/questions/2848704/postgresql-running-python-stored-procedures-as-a-normal-user

**Comment by chrismre** [comment]
@netj can you setup a Skype with @vsoch, let's make sure this is resolved :)

**Comment by vsoch** [comment]
I think we should be able to set up a dedicated database with superuser - I will know more information on Monday! If not, it would definitely be worth a chat. I can imagine many scenarios of wanting to use DeepDive without any kind of sudo.

**Comment by vsoch** [comment]
Once I know more about the database, it might be needed to setup a Skype to talk about the different options for setting this up to run in parallel. I have a few ideas, will likely try a few things, and very likely will have questions!

**Comment by chrismre** [comment]
I think the plpython dependency is gone (or will be soon). @netj can
confirm :)

**Comment by vsoch** [comment]
+1 !

**Comment by zhangce** [comment]
@chrismre The default plpythonu dependency is scheduled to be removed in the coming release (~this weekend?) If users need it, they can install it by themselves; but by default, DD will not require `sudo` very soon.

**Comment by vsoch** [comment]
@zhangce, wicked awesome. Looking forward to it.

**Comment by vsoch** [comment]
Hi Hazy! Any updates on superuser? Did you mean this passed weekend, or next weekend? We are paused in developing on TACC so I wanted to make sure that I didn't miss the update!

**Comment by netj** [comment]
Hi @vsoch, a new release is out ([v0.7.1](https://github.com/HazyResearch/deepdive/releases/tag/v0.7.1)) which removed the plpythonu dependency for postgresql.  Can you see if that helps?  You can use the same installation instruction to get the latest release:
```bash
bash <(curl -fsSL deepdive.stanford.edu/install)
```

**Comment by vsoch** [comment]
Excellent! I will update this morning and let you know if I run into trouble.

**Comment by netj** [comment]
Let me know if you want to look into any of your problem together.  I can Hangout/Skype later in the afternoon PT.  I'll send a direct email.

**Comment by netj** [comment]
I think using v0.7.1 resolved this issue (although we had to use more workaround for SSL).
