### ISSUE TITLE
Lost data with spouses example

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#413]
With spouses example.i run 2 SQL queries:
- select count(*) from has_spouse >> Result:75422
- select count(*) from has_spouse_is_true_inference >> Result :70969
So we have lost some data right???(lost some has_spouses_candidates after deepdive inference)??Is it an bug??How to fix it?

**Comment by alldefector** [comment]
@astrung that might be a symptom of https://github.com/HazyResearch/deepdive/issues/416

Namely that 75422 - 70969 tuples were "supervised".

**Comment by feiranwang** [comment]
The default setting is that deepdive only output probabilities for non-evidence variables. If you also want to see the probabilities for evidence variables, you can turn on the `--sample_evidence` flag in the sampler. Please refer to http://deepdive.stanford.edu/doc/basics/configuration.html#sampler and http://deepdive.stanford.edu/doc/basics/sampler.html.

**Comment by astrung** [comment]
But what is "evidence variables"??Even with some variables with same values(with spouses examples,it have same persons 1 and persons 2),some variables is not in output??I thinh that "evidence" is training data and testing data????

**Comment by alldefector** [comment]
Closing this following #416
