### ISSUE TITLE
DDLOG fails when views depend on views

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#421]
Consider the following DDLOG snippet:
```
wordidxs_unnested(doc_id, sent_id, UNNEST(wordidxs)) :-
  locations(id, doc_id, sent_id, wordidxs, mention_id, type, entity, words, is_correct, features).

wordidxs_tmp1(doc_id, sent_id, MIN(wordidxs) - 1) :-
  wordidxs_unnested(doc_id, sent_id, wordidxs).
```
Running this program the second time crashes DeepDive, because it cannot drop view ``wordidxs_unnested`` (view ``wordidxs_tmp1`` depends on it).

There may be a better fix, but one work-around is to generate ``deepdive.conf`` and append ``CASCADE`` to
```
DROP VIEW IF EXISTS wordidxs_unnested;
```

**Comment by juhanaka** [comment]
I can take a look at this.

**Comment by netj** [comment]
@juhanaka awesome!  You'll need to see https://github.com/HazyResearch/ddlog to fix the compiler.
