### ISSUE TITLE
DDLOG does not run analyze, sometimes executes bad query plans

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#422]
Our ddlog contains:
```
@weight(feature)
locations_inference(mention_id) :-
  locations(id, doc_id, sent_id, wordidxs, mention_id, type, entity, words, is_correct, features),
  locations_unnested(mention_id, feature),
  LocationsFeatureCount(feature, cnt),
  cnt > 1.
```
which gets translated into
```sql
CREATE TABLE dd_query_inference_rule_0 AS 
  SELECT R0.id AS "locations_inference.R0.id" , R2.column_1 AS "dd_weight_column_0" 
  FROM locations_inference R0, locations R1, locations_unnested R2, LocationsFeatureCount R3
  WHERE R1.mention_id = R0.mention_id AND R2.column_0 = R0.mention_id AND R3.feature = R2.column_1 AND R3.cnt > 1
```
The query plan that gets executed performs three hash joins and is very slow. After manually running analyze on each table, the same query yields a more efficient plan with three merge joins. 

Not sure how to solve this in DDLOG: always run analyze? allow users to force analyze?

**Comment by SenWu** [comment]
@raphaelhoffmann We will always run `ANALYZE TABLE_NAME` after each extractor. For example, in tsv extractor, we have https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/extraction/ExtractorRunner.scala#L509.

**Comment by raphaelhoffmann** [comment]
@SenWu Thanks! It looks like we ran into an issue with PGXL, not DDLOG. 

After restarting PGXL, the time for this query went down from 38 min to 3 min, and the query plans were good again. (We kept the old logs and query plans both before/after analyze in case they are useful.) Due to this and other issues, we decided to move our processing back to Greenplum.
