### ISSUE TITLE
DDLOG app no longer compiles with latest release

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#423]
Many of our extractors have the following DDLOG structure:
```
candidates(
  id bigint,
  doc_id text,
  is_true boolean,
  features text[]
).

candidates_inference?(doc_id text).

candidates_unnest(id, doc_id, is_true, UNNEST(feature)) :-
  candidates(id, doc_id, is_true, feature).

@label(is_true)
candidates_inference(doc_id) :- candidates_unnest(id, doc_id, is_true, feature).

@weight(feature)
candidates_inference(doc_id) :-
  candidates_unnest(id, doc_id, is_true, feature).
```

This worked fine until the latest release 0.7.1., but now I'm getting
```
$ ddlog compile app.ddlog
[error] key not found: candidates_unnest
```
If I use a deepdive build based on a commit from 3 days ago (84898b1c9b9337a64057c521def5008b34d8913f),  it works fine.

Did the DDLOG syntax change?

**Comment by chrismre** [comment]
@netj @zhangce What's going on here?

**Comment by zhangce** [comment]
@raphaelhoffmann Where did you define the relation `candidates_unnest` in the program?

**Comment by feiranwang** [comment]
Looking into this.

**Comment by zhangce** [comment]
@raphaelhoffmann Can you give us the full program to reproduce this? The program you provided should throw this error because you do not give ddlog the schema of `candidates_unnest `...

**Comment by feiranwang** [comment]
@netj Hi Jaeho, I checked this program works on my recent ddlog, and it seems this problem occurs after merging seojiwon's HazyResearch/ddlog#56.

**Comment by chrismre** [comment]
Oh no! Can we get that fixed =)

**Comment by netj** [comment]
The new type checker for supervision columns seems to be the cause. I think using undeclared relations shouldn't be allowed eventually but we can get the type checker quickly fixed to skip undeclared relations for now. @seojiwon Can you make a fix?

**Comment by zhangce** [comment]
@raphaelhoffmann Sorry for the confusion, I didn't know that in ddlog we can use a relation without declare its schema.

**Comment by netj** [comment]
@raphaelhoffmann Thanks for reporting.  I'll create a maintenance release tomorrow.

Btw, do you think it's useful to have an automated binary build of master (and every maintenance branch, e.g., v0.7.x)?  It can free you from going through a tedious source build and we won't have to create a bunch of hotfix releases for these small bug fixes.
