### ISSUE TITLE
How to run second extractor and inference after first inference 

### ISSUE THREAD

**Issue by astrung** [HazyResearch/deepdive#424]
i have 2 inference variables,but second inference variable get first inference variable as an input,so i want to run a pipeline like that:
Inference variables:{A,B}
- Extractor A mentions
- Inference for A variables
- Extractor B mentions(get high expectation of A variable as it input)
- Inference for B variables
Does deepdive support it????And how to do that???

**Comment by netj** [comment]
Unfortunately, you have to create two DeepDive applications for that, first running one for A, then taking extractions to run another for B.  However, we strongly recommend to stay within a single app to do "joint inference" by expressing the correlations between all variables in A and B within one factor graph.
