### ISSUE TITLE
If an extractor depends on inference, DD halts indefinitely before doing inference

### ISSUE THREAD

**Issue by Colossus** [HazyResearch/deepdive#427]
At least stop with an error ... please. What's currently happening is that the output looks exactly like inference (with lines like

    09:10:33 [taskManager] INFO  Memory usage: 539/1809MB (max: 233017MB)

getting output every minute and nobody knows what's going on.

(ACTUALLY, I'd propose ALLOWING extractors after inference. MY particular extractor was for printing precision and recall numbers after every run. Prolepsis: This SHOULD be in Dashboard, and it's going to be there, but it's just nice to have a precision number immediately after a run, in the DD log output.)

**Comment by chrismre** [comment]
@netj @zhangce we should fix this!

**Comment by alldefector** [comment]
Related: #424

Support for result pipelining would be great. Looks like a key challenge would be to cleanly model the "result" (see #416).
