### ISSUE TITLE
Possible to get rid of UDF input data splitting?

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#428]
We ran a simple extractor that basically just takes phrases with the NER tag PERSON over 30M documents (about 200GB in terms of sentences table size). Here is a breakdown of the time spent:

COPY OUT (with ARRAY_TO_STRING): 30 min
split: 35 min
UDF: 10 min (70 threads)
COPY IN: 20 min

First, some small perf comments:
1. Wonder whether we could speed up COPY OUT significantly if we could get rid of ARRAY_TO_STRING one day...
2. DD by default seems to split the UDF input data into small files with 10K lines each. The DDLog syntax doesn't seem to support the specification of the UDF input batch size. Following @SenWu 's suggestion, we used a larger batch size (100K lines), and `split` ended up taking 35 min. Not sure if it would be much faster if we use an even larger batch size. Small batch sizes have two issues: a) too many files making `split` itself slow; b) if the UDF has a slow init step, that init overhead is multiplied by the number of splits. Of course, if the batch size is too large, and the number of splits << number of cores, we under-parallelize. Maybe we could do some adaptive splitting; e.g., split into 100MB chunks, and if it ends up having too few chunks, further split each chunk so that the total number of chunks ~= number of cores.

And the big comment:

Is it possible to get rid of the file splitting step altogether? If we could pipe COPY OUT | UDF | COPY IN all in memory, we might be able to run the above program in 20 min instead of 100 min. ( @netj had some great hacks that seem to be in this direction https://github.com/netj/mkmimo . Has that been applied in DD anywhere?)

**Comment by netj** [comment]
Here's the script in an ancient branch that was going to replace the generated exec_parallel.sh scripts, avoiding materializing any split inputs to do udfs: https://github.com/HazyResearch/deepdive/blob/netj-inmemory-extraction/util/run_parallel.sh

The extraction part needs a complete rewrite IMO. Dependencies don't make sense, parallelizing is suboptimal, akka fills up the log with noise. Especially Splitting into fixed size chunks incurs unnecessary udf process startup costs, and spilling them requires extra storage.

If this is a blocker for you, I think you can workaround using the above script.  Make sure you use the c branch of mkmimo.
