### ISSUE TITLE
Tutorial: integrate external extractors with DeepDive

### ISSUE THREAD

**Issue by chrismre** [HazyResearch/deepdive#429]
Nigam Shah made the point that we should make it easier for people to integrate external extractors that they written in DeepDive. In antiquity, this was actually the first design of DeepDive, but now it is quite mysterious.... 

Can someone write a tutorial about how to do this in ddlog? @netj @feiranwang 

Follow up with Nigam for an example.

**Comment by netj** [comment]
We now have a dedicated [UDF doc](https://github.com/HazyResearch/deepdive/blob/ec648595c431385b601a317ca73de191bd4adb91/doc/writing-udf-python.md) that implies how to plug in these general extractors, then highlighting our Python support.  Maybe we can write another section about general udfs.  The new spouse example in fact already includes such non-Python but Java/Scala extractor (CoreNLP):  [`nlp_markup.sh`](https://github.com/HazyResearch/deepdive/blob/ec648595c431385b601a317ca73de191bd4adb91/examples/spouse/udf/nlp_markup.sh) with [its DDlog counterpart](https://github.com/HazyResearch/deepdive/blob/ec648595c431385b601a317ca73de191bd4adb91/examples/spouse/app.ddlog#L34-L64).  So it's really a matter of writing about them, or maybe the page already is clear enough?

**Comment by alldefector** [comment]
OK, UDFs are language-agnostic and decoupled from DD core (only connection is command line string in ddlog and data pipes at runtime). @netj we should probably emphasize these points in the next version of docs. Feel free to close either now or when doc is updated.
