### ISSUE TITLE
Why Blank ID for "has_relation" example?

### ISSUE THREAD

**Issue by vsoch** [HazyResearch/deepdive#430]
I'm hitting a bug that the "id" variable is null (and it breaks a requirement of not null) when I am trying to perform inference:

          SELECT sentence_id FROM sentences WHERE RANDOM() < 0.25
          19:38:50 [PostgresDataStore(akka://deepdive)] DEBUG Executing query via JDBC: INSERT INTO dd_graph_variables_holdout(variable_id)
          SELECT id FROM has_related_concept WHERE sentence_id IN
          (SELECT * FROM holdout_sentence_ids)
          19:38:50 [PostgresDataStore(akka://deepdive)] ERROR org.postgresql.util.PSQLException:     ERROR: null value in column "variable_id" violates not-null constraint
          Detail: Failing row contains (null).
          19:38:50 [taskManager] INFO  Completed task_id=inference_grounding with Failure(org.postgresql.util.PSQLException: ERROR: null value in column "variable_id" violates not-null constraint
          Detail: Failing row contains (null).)
         19:38:50 [profiler] DEBUG ending report_id=inference_grounding
         `19:38:50 [taskManager] ERROR task=inference_grounding Failed: org.postgresql.util.PSQLException: ERROR: null value in column "variable_id" violates not-null constraint`
         Detail: Failing row contains (null).
         19:38:50 [taskManager] ERROR Forcing shutdown
         19:38:50 [taskManager] ERROR Cancelling task=inference
         19:38:50 [taskManager] ERROR Cancelling task=calibration
         /home/02092/vsochat/local/util/deepdive-run: line 132: 126016 Killed                  java org.deepdive.Main -c "$fullConfig" -o "$run_dir"

However, in the function to extract relations (specifically, "has_related_concept" that is in line with the "has_spouse" example, the [instruction is to](https://github.com/HazyResearch/deepdive/blob/master/examples/tutorial_example/step1-basic/udf/ext_has_spouse.py#L57) "leave the ID blank for DeepDive"

        # Output relation candidates into output table
        print '\t'.join([
        p1_id, p2_id, sentence_id,
         "%s-%s" %(p1_text, p2_text),
         is_true,
          "%s-%s" %(p1_id, p2_id),
         '\N'   # leave "id" blank for system!
         ])

and so it's logical that my "id" variable is blank:

      deepdive sql "select id from has_related_concept;"
       id 
      ----
   
- Here is the script to run the extraction for [has_related_concept](https://github.com/vsoch/neurosynth-nlp/blob/master/udf/ext_has_related_concept.py)
- Here is the [function to do the inference](https://github.com/vsoch/neurosynth-nlp/blob/master/deepdive.conf#L116)

The tables look ok to me, but please let me know if you'd like to see anything:

      login1.wrangler(34)$ deepdive sql "\d+"
                                    List of relations
       Schema |              Name              |   Type   |  Owner  |    Size    | Description 
      --------+--------------------------------+----------+---------+------------+-------------
       public | articles                       | table    | vsochat | 16 MB      | 
       public | concept_mentions               | table    | vsochat | 9520 kB    | 
       public | dd_graph_variables_holdout     | table    | vsochat | 0 bytes    | 
       public | dd_variable_sequence           | sequence | vsochat | 8192 bytes | 
       public | dummy                          | table    | vsochat | 8192 bytes | 
       public | has_cognitive_concept          | table    | vsochat | 0 bytes    | 
       public | has_cognitive_concept_features | table    | vsochat | 0 bytes    | 
       public | has_related_concept            | table    | vsochat | 56 MB      | 
       public | has_related_concept_features   | table    | vsochat | 629 MB     | 
       public | holdout_sentence_ids           | table    | vsochat | 928 kB     | 
       public | region_mentions                | table    | vsochat | 2344 kB    | 
       public | sentences                      | table    | vsochat | 150 MB     | 
      (12 rows)

Here are a few from has_related_concept:

      concept1_id   |  concept2_id   | sentence_id |                description                 | is_true |          relation_id          | id 
      ----------------+----------------+-------------+--------------------------------------------+---------+-------------------------------+----
       21103006@0_12  | 21103006@0_19  | 21103006@0  | decis-expect                               |         | 21103006@0_12-21103006@0_19   |   
       21103006@0_19  | 21103006@0_12  | 21103006@0  | expect-decis                               |         | 21103006@0_19-21103006@0_12   |   

We have true and false defined

      deepdive sql "SELECT is_true, COUNT(*) FROM has_related_concept GROUP BY is_true" 

      is_true |       count  
      ---------+--------
               | 459012
       t       |  33774
       f       |  30458
      (3 rows)

Note that we don't actually have any false examples, but I generated some to debug in case that was the issue.

Holdout sentence ids are specified

       sentence_id 
      -------------
       18702583@1
       25463814@5
       22465459@0

Features look ok:

      deepdive sql "select * from has_related_concept_features;"
 

                relation_id          |                     feature                      
      -------------------------------+--------------------------------------------------
       23861319@5_25-23861319@5_31   | word_between=bilateral
       23861319@5_25-23861319@5_31   | word_between=pallidum
       23861319@5_25-23861319@5_31   | word_between=putamen

Any ideas of the bug? Or what I could try to further test it? I think we are close to getting that cool web report!! And next I am also going to derive relations between brain regions and concepts, which will have a better base of positive and negative examples to train from :O)

**Comment by netj** [comment]
@vsoch The ids are supposed to be assigned before running your holdout query.  Not sure why it didn't.

@feiranwang Any idea why the ids for the variables table can remain null when executing the [holdout query](https://github.com/vsoch/neurosynth-nlp/blob/master/deepdive.conf#L157-L164)?

**Comment by feiranwang** [comment]
@vsoch The problem is that variable relation `has_related_concept` is not declared in `schema.variables`.

**Comment by vsoch** [comment]
Ah! That's what I get for renaming my pipeline to `has_related_concept` from `has_cognitive_concept`...

oh my gosh!! It's working!! It's working!!

**Comment by vsoch** [comment]
Thanks for the help, you just made my Friday and brought immense happiness :O)

**Comment by feiranwang** [comment]
That's awesome! :)
