### ISSUE TITLE
Why remove tasks dependencies that are not in the pipeline?

### ISSUE THREAD

**Issue by dshore** [HazyResearch/deepdive#431]
What is the rationale for removing task dependencies not specified in the pipeline?
https://github.com/HazyResearch/deepdive/blob/master/src/main/scala/org/deepdive/DeepDive.scala#L148

By always removing the dependencies one is forced to resolve the dependency graph manually and add to the pipeline.  I do see the benefit of allowing the pipeline definition to override dependencies but it seems this should not be the default behavior.

I may create a PR to add a runtime arg to control this... I am eager to get in a commit!

**Comment by netj** [comment]
Sorry, the current dependency handling is largely broken, and most power users so far preferred to manually manage their pipelines.  I completely agree this shouldn't be the default, and we'll get this fixed pretty soon as we get rid of Akka.  We're going to refactor the extractor runner part to easily support various compute environments other than local processes, so we'll definitely take dependencies more seriously.  Your help–code or comments–will be appreciated!
