### ISSUE TITLE
ddlog support for inference with pre-learned weights

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#433]
Currently ddlog does not support doing inference with pre-learned weights, which is supported by the low-level configuration of `skip_learning` and `weight_table` parameters.

**Comment by netj** [comment]
Could you describe ideally how you want to run just the inference with the learned weights, e.g., at the level of `deepdive` command? Maybe we need a separate `deepdive learn` and/or `deepdive infer` commands? But you'd want to run extraction for new variables right?

**Comment by netj** [comment]
Done by #481
