### ISSUE TITLE
Docs for doing inference with pre-learned weights seems missing

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#434]
The docs for using parameters `inference.skip_learning` and `inference.weight_table` seems missing from the website. One should need them when using pre-learned weights to do inference on new data.

**Comment by netj** [comment]
Done in https://github.com/HazyResearch/deepdive/blob/3997a8d3b9fd78ff3fe8b3bbd86803889d411451/doc/ops-model.md#reusing-weights regarding #481
