### ISSUE TITLE
update the sampler document

### ISSUE THREAD

**Issue by SenWu** [HazyResearch/deepdive#439]
Please update the doc about sampler args.

The sampler accepts two different input formats:
1.Original mode: sampler uses new input format(variable file, factor file, and weight file; no edge file).
2.Incremental mode: sampler uses the old input format(variable file, factor file, and weight file, and edge file).

For new input format:
1. The format of variable file and weight file are the same.
2. The format of factor file is as follow:
weight_id, type, equal_predicate, edge_count, variable_id_1, padding_1, ..., variable_id_k, padding_k
Also it is binary without delimiter.

**Comment by netj** [comment]
@SenWu could you reflect this change to the docathon-v0.8 branch?  I think we should primarily document the original mode, and keep as a small note of the difference for inc mode at the end.

https://github.com/HazyResearch/deepdive/blob/docathon-v0.8/doc/factor_graph_schema.md

**Comment by netj** [comment]
Done in 1831e39ceeea9041e9bc77f32b35809376b22051
