### ISSUE TITLE
no install instructions for building from source

### ISSUE THREAD

**Issue by hartsantler** [HazyResearch/deepdive#441]
so after i git clone this repo, then what?

http://deepdive.stanford.edu/doc/basics/installation.html

that page says nothing about doing a git clone and how to build from scratch.

**Comment by netj** [comment]
See the [developer's guide](http://deepdive.stanford.edu/doc/advanced/developer.html#build-test) linked from that page.

**Comment by netj** [comment]
The link is buried in the middle of the text and not very visible.  We'll make it clearer.  Thanks for your feedback!
* [ ] add a *build from source* section to installation page
* [ ] document build dependencies in developer's guide

**Comment by hartsantler** [comment]
i ran `make depends` if first prints out that Fedora is not supported,
then reminds me that i needs to install: git, make, bzip2, unzip and jdk, (which i already have), and then it prompts me if i want to continue.  I have to type `y`,
then it asks me again to make sure i have: bash, coreutils, xargs, bc, gnuplot, jre, and python (i have all these already).

i wish that it would not prompt me to type `y` and just run, that way i can make an automated script to get the repo and rebuild from scratch.  how do i make a fully automated script when it asks multiple times for me to type `y`?

**Comment by netj** [comment]
Done in e54092a76a3efb75889c704fdd817fb9fe3a9379 and f8e1353d8d7406adfdc2ce0fdcb592ef8772a412, and they'll appear in the next release.
