### ISSUE TITLE
build from source fails on fedora22

### ISSUE THREAD

**Issue by hartsantler** [HazyResearch/deepdive#442]
i ran `make depends` and then `make`, below is the error from `make`.
```bash
make[1]: Entering directory '/home/brett/deepdive/sampler'
g++ -o src/gibbs.o  -std=c++0x -Wall -fno-strict-aliasing -I./lib/tclap/include/ -I./src -Ofast -I./lib/numactl-2.0.9/ -c src/gibbs.cpp
In file included from src/gibbs.h:4:0,
                 from src/gibbs.cpp:2:
src/common.h:8:18: fatal error: numa.h: No such file or directory
compilation terminated.
Makefile:79: recipe for target 'src/gibbs.o' failed
make[1]: *** [src/gibbs.o] Error 1
make[1]: Leaving directory '/home/brett/deepdive/sampler'
Makefile:110: recipe for target 'build-sampler' failed
make: *** [build-sampler] Error 2
```

**Comment by netj** [comment]
You need to have libnuma-devel installed and use gcc >= 4.8.  These were recently added dependencies to the master branch as we started to build sampler from source.  You can also stick to the v0.7.x branch which don't need them.

**Comment by hartsantler** [comment]
thanks netj, i got deepdive to compile.
note that in the new fedora the libnuma-devel package has been renamed to:
numactl-devel

**Comment by vipulved** [comment]
On recent Ubuntu, this package is called libnuma-dev.

**Comment by netj** [comment]
Btw libnuma-dev gets installed on Ubuntu when you ask [the installer](https://github.com/HazyResearch/deepdive/blob/master/doc/installation.md#quick-installation) for build dependencies.

And now installer knows which yum packages to install on some RedHat-based distros.
