### ISSUE TITLE
org.apache.commons.dbcp error

### ISSUE THREAD

**Issue by billgreenwald** [HazyResearch/deepdive#443]
While installing deepdive from the github (using the jdbc_removal branch, though the error looks to be in multiple branches) I hit the following error

[error] /home/bill/nonjdcb-deepdive/deepdive/src/main/scala/org/deepdive/datastore/PostgresDataStore.scala:25: object dbcp is not a member of package org.apache.commons
[error]       val del = new org.apache.commons.dbcp.DelegatingConnection(connection)

changing the line in the PostgresDataStore.scala file to

val del = new org.apache.commons.dbcp2.DelegatingConnection(connection)

seemed to fix the problem.  I'm running java version 1.7

**Comment by netj** [comment]
Thanks for reporting.  This has been fixed in the master via 49c0bd478d22fc26ae4913c0add94ca3577311d7.  You could also merge or cherry-pick it in the jdbc_removal branch.

**Comment by elvin2014lee** [comment]
Thanks a lot !!!!!!! I encountered the same problem as you .
