### ISSUE TITLE
Gibbs sampler does not seem to support multiple regularisation parameters

### ISSUE THREAD

**Issue by paidi** [HazyResearch/deepdive#454]
The walkthrough in the documentation states that

> The Gibbs sampler in DeepDive accept one or more --reg_param VALUE options that can be used to specify a set of possible regularization values. The system will use 2-fold cross validation on the training set to select the best parameter value among those specified. A technical detail: the best parameter, as chosen by the system, is the one with the highest harmonic mean of the F1-score in the cross validation.

However, when running the code in [step2-generic-features](https://github.com/HazyResearch/deepdive/tree/master/examples/tutorial_example/step2-generic-features) I received an error due to the Gibbs sampler being called with multiple `reg_param` parameters set.

**Comment by netj** [comment]
Sorry for the confusion.  That feature (#184) has been dropped a while ago due to a bug (#204) and the documentation/example hasn't been updated properly.  For the moment, please stick to using a single `--reg_param` option.  We'll update the doc and examples very soon.

**Comment by paidi** [comment]
Thanks @netj. That was what I figured and have completed the walkthrough using a single `--reg_param`

**Comment by netj** [comment]
It now takes multiple, but just uses the last.  See #204 for automatic selection of the parameter.  Closing this instead.
