### ISSUE TITLE
categorical variables do not work with --sample_evidence

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#462]
If you run the chunking example with "--sample_evidence" two unexpected things happen:
1. Most expectations returned by the sampler are NaN.
2. The final calibration query fails. 
Is there an easy fix for that?

**Comment by feiranwang** [comment]
Will fix this soon.

**Comment by netj** [comment]
@raphaelhoffmann I'll bring the fix into master and v0.7.x soon.  For the moment, you can manually point your submodule to it.

**Comment by raphaelhoffmann** [comment]
@feiranwang @netj Wow, thanks guys, for fixing this so quickly!
