### ISSUE TITLE
Missing warning when using int instead of bigint for id column

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#466]
When you define the schema for a candidate table, you can use int as the datatype for your id column. In that case DeepDive will run, but it will be much slower than if you choose bigint. This is because joins with internal tables cannot be as efficiently executed when the datatypes don't match. It would be great if DeepDive could show a warning or throw an error when the datatype is not bigint.

**Comment by netj** [comment]
Is this applicable to ddlog? Or when using deepdive.conf directly?

**Comment by raphaelhoffmann** [comment]
I noticed when using deepdive.conf, but I think the issue applies to ddlog as well.

**Comment by netj** [comment]
The internal ids are at least always bigint I believe but for other fields giving warnings sounds good.

**Comment by alldefector** [comment]
Var IDs are now no longer exposed to the user schema space.
