### ISSUE TITLE
Docker-compose / Docker

### ISSUE THREAD

**Issue by lucmichalski** [HazyResearch/deepdive#467]
Hi guys,

Hope you are doing well !

Is there any dockerfile or docker compose template available for deepdive ?

That would be amazing :-)

Cheers,
Luc Michalski

**Comment by skprasadu** [comment]
There is this link, please see if it is useful.. for me somehow, the linking between Postgres and Docker was not working.. 

http://deepdive.stanford.edu/doc/advanced/docker.html

If you make it work, please let me know how it works.

Thanks
Krishna

**Comment by netj** [comment]
See also #231 for past attempts of Docker support.  We will be looking into this at some point, but if you can contribute a Dockerfile that would be awesome!

**Comment by joshneland** [comment]
I have a working dockerfile to commit, but it's having a problem with the spouse_example in 0.8 that I'm troubleshooting first.

**Comment by lanphan** [comment]
@joshneland @netj 
Is there any progress on this task? I have some free time this weekend, and I already have Deepdive Docker to share with you. Just need some time to verify and add Docker Compose.
