### ISSUE TITLE
Automatically run `deepdive compile` when necessary

### ISSUE THREAD

**Issue by netj** [HazyResearch/deepdive#470]
Currently, the user has to remember to manually run `deepdive compile` after making changes.  Some users want `deepdive do` to be smarter and conservatively compile by itself when needed.  The process timestamps can be invalidated whenever the user switches database or makes changes to the udf files.  The data timestamps may well be kept per db.url and we could rely on git to detect changes to files as well.  However, ultimately the user should decide to compile or not, so maybe it can simply show a warning or ask to recompile interactively.

**Comment by alldefector** [comment]
I'd prefer DD to auto compile by default since that's the most common use case.
