### ISSUE TITLE
Scaling for factor graphs that are 100TB 

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#478]
We've encountered grounding results that Zifei had to run with a 900GB-RAM machine because the 300GB-RAM machine wasn't big enough for the factor graph.

But the factor graph consists of millions of small connected components (say one per document), so we should need no more than 64KB of memory if we process the components one by one (not including space for the model). In fact, a lot of existing programs have graphs consisting of singleton variables...

We don't even need to detect those components -- this pattern is so common that we could introduce some syntax in DDLog to provide hints; e.g., telling DD that doc_id can be used as a partition key.

Resolves #256

**Comment by chrismre** [comment]
This was a very old feature... where did this go @zhangce @netj @SenWu 

You don't even need syntax for this, it's easy to detect... @feiranwang

**Comment by SenWu** [comment]
I will sync with Zifei and push this feature in another branch.

**Comment by chrismre** [comment]
Zifei is out of the country.  :)

Is this code stable? I thought you built this months ago! Has it been code reviewed?

Also, @netj and @feiranwang, it should be super easy to declare categorical that are linked (say for our old entity linking design, they **need** to be able to express 

LinksToOne(candidate, entity) as a categorical random variable (each candidate maps to one entity). 

This should be super easy (@key is fine). @zhangce, I know you're traveling but your thoughts are welcome when you get back on line :)

@ajratner I don't want to redo the full constraints--no one seem to use them, and they have lots of code complexity... maybe in the summer :)

**Comment by SenWu** [comment]
I am not sure it is stable. I only test it on small examples (around 100k docs). But this is really a good opportunity to test my code and put it in. I am talking to Feng about the case. :)

**Comment by chrismre** [comment]
Ha, OK :)

**Comment by chrismre** [comment]
Sen, how are we doing here?

**Comment by SenWu** [comment]
Yes, I have already synced with Feng and I will add partition support based on DD v0.8. And I briefly talked with Jaeho about it yesterday and we will come up a concrete plan for it on Wednesday.

**Comment by alldefector** [comment]
@SenWu Any update?

We have an app with 100K docs, 13M vars, 42M weights, 248M edges, and 242M factors. The machine has 2 NUMA nodes. DD was stuck at `CREATE FG ON NODE ...1` for over an hour with the sampler using 70GB of RAM and the machine apparently thrashing...

```
2016-02-23 17:58:50.972139 ################################################
2016-02-23 17:58:50.972150 # nvar               : 13447656
2016-02-23 17:58:50.972162 # nfac               : 242889469
2016-02-23 17:58:50.972175 # nweight            : 42308790
2016-02-23 17:58:50.972187 # nedge              : 248001424
2016-02-23 17:58:50.972200 ################################################
2016-02-23 18:02:27.024966 LOADED VARIABLES: #13447656
2016-02-23 18:02:27.025074          N_QUERY: #11900206
2016-02-23 18:02:27.025096          N_EVID : #1547450
2016-02-23 18:02:47.727552 LOADED WEIGHTS: #42308790
2016-02-23 18:05:38.553535 LOADED FACTORS: #242889469
2016-02-23 18:09:43.023361 CREATE FG ON NODE ...1
```

**Comment by SenWu** [comment]
@BrettMeehan is making progress now. Brett, could you give us some updates here? Thanks.
BTW: for large factor graph, I suggest using only 1 numa node(the sampler argument is -c 1).

**Comment by alldefector** [comment]
Yes, the sampler uses 40GB of memory with `-c 1` and works for now. But we have at least 50X as many docs. So partitioning is critical.

**Comment by chrismre** [comment]
How did we lose the ability to bring connected components into memory?

This needs to be fixed soon... Let's talk about this in dev meeting.

**Comment by BrettMeehan** [comment]
@SenWu I'm curently working on adding checkpointing to the learning and inference steps of the Gibbs sampler so the application can be paused and resumed. Also browsing Feiran's partition code from 1 year ago to see what parts we can merge to the main branch.
