### ISSUE TITLE
app.ddlog spouse example

### ISSUE THREAD

**Issue by thodrek** [HazyResearch/deepdive#486]
@netj  spouse_label(p1, p2) = NULL :- spouse_candidate(p1, _, p2, _). 
Does not compile switch to spouse_label(p1, p2,0,NULL):- spouse_candidate(p1, _, p2, _).

**Comment by netj** [comment]
I think this was fixed in docathon branch by putting `NULL::BOOLEAN`. I'm not entirely clear if this is ok right now (potentially putting duplicates) but this is how it should be written in my view.

**Comment by thodrek** [comment]
OK but we need to make sure cause I tried compiling and it gave me an error.

**Comment by netj** [comment]
Could you post the error line, for reference?
