### ISSUE TITLE
sampler segfault with docathon-v0.8

### ISSUE THREAD

**Issue by raphaelhoffmann** [HazyResearch/deepdive#489]
The recent updates to the sampler crash my runs (eg. on chunking example):

```
PROB BIN 0.7~0.8  -->  # 0
PROB BIN 0.8~0.9  -->  # 0
PROB BIN 0.9~0.10  -->  # 2317
process/model/learning/run.sh: line 22: 66591 Segmentation fault      (core dumped) sampler-dw gibbs -w <(flatten factorgraph/weights) -v <(flatten factorgraph/variables) -f <(flatten factorgraph/factors) -m factorgraph/meta -o weights -l 5 -s 1 -i 5 --alpha 0.1 -c 0 --sample_evidence
```

However, when I roll back the sampler to a [previous commit](https://github.com/HazyResearch/sampler/commit/4b9ff5dca660c466c128bef85e9371e5670a4adb) but leave the rest of deepdive current on docathon-v0.8, it's working fine.

**Comment by netj** [comment]
Have you tried a clean build of the new commit? The header dependency is not accurate and resulting in corrupted executable when built incrementally..

**Comment by raphaelhoffmann** [comment]
Great! That worked!
