### ISSUE TITLE
If two factors have similar heads, "do weights" loads one of the factor weights arbitrarily

### ISSUE THREAD

**Issue by Colossus** [HazyResearch/deepdive#492]
I have two different factors in app.ddlog that start with the head

    @weight("?")
    genepheno_causation_inference(relation_id_left), genepheno_causation_inference(relation_id_right) => !genepheno_causation_inference(relation_id_inner) :-

    @weight("?")
    genepheno_causation_inference(relation_id_left), genepheno_causation_inference(relation_id_right) => !genepheno_causation_inference(relation_id_outer) :-

because the heads are similar, both factors end up getting loaded in a database table called `dd_weights_inf_imply_genepheno_causation_inference_genepheno_ca` (sic). I hope that in the underlying factor graph, both factors are present; but after `deepdive do weights` I can only check on the weight of one of these factors.

**Comment by netj** [comment]
Looks like the long names truncated can cause some unintended consequences. We'll need to support ways to prevent this by hashing the full name to a fixed length etc. along with a way to annotate rules with a user defined name.

**Comment by netj** [comment]
This seems related to #276
