### ISSUE TITLE
Compilation failed of spouse exemple

### ISSUE THREAD

**Issue by naddou14** [HazyResearch/deepdive#505]
Hello,
I'm new with Deepdive and I was trying to install and test it. The installation has been done successfully but I have found problems with spouse example (I’m following this tutorial http://deepdive.stanford.edu/example-spouse#4-error-analysis-and-debugging). 
So when I do "deepdive do articles" I have this error: 
[error] error while loading AnnotationPipeline, class file '/home/nadia/.ivy2/cache/edu.stanford.nlp/stanford-corenlp/jars/stanford-corenlp-3.5.1.jar(edu/stanford/nlp/pipeline/AnnotationPipeline.class)' is broken
2016-02-26 13:22:11.799106 [error] (class java.lang.NullPointerException/null)
2016-02-26 13:22:19.732839 [warn] one warning found
2016-02-26 13:22:19.733805 [error] one error found
2016-02-26 13:22:19.848327 [error] (compile:compileIncremental) Compilation failed
2016-02-26 13:22:19.853934 [error] Total time: 42 s, completed Feb 26, 2016 1:22:19 PM

Can you help me please?

Thank you,
Nadia

**Comment by alldefector** [comment]
You are probably running Java 7. CoreNLP requires Java 8.

@netj We've encountered the same problem a couple of days ago. We should probably add some Java version validation code in the example code.

**Comment by naddou14** [comment]
Thank you alldefector :) It was exactly the problem

**Comment by netj** [comment]
@alldefector The docs are going to be updated by #506, but we can definitely add some checks to the example script.  Another big pitfall is not having wget installed on Mac, which leads to silently passing over a Bazaar/Parser setup error (the english SR parser download).  Will propose a fix there too.
