### ISSUE TITLE
Running DeepDive tests on EC2

### ISSUE THREAD

**Issue by sandipchatterjee** [HazyResearch/deepdive#517]
(creating an issue for this because I assume AWS/EC2 is a common setup for DeepDive usage...)

After installing DeepDive and Postgres on a fresh Ubuntu 14.04 EC2 instance using `bash <(curl -fsSL git.io/getdeepdive)` -- running DeepDive tests from the installer script (option 8 for **run_deepdive_tests**) results in several tests failing just because `make` isn't available.

This is easily solved by installing `make`, etc. with `sudo apt-get install build-essential`

Just thought a note about this in the documentation might be helpful so that users don't assume DeepDive isn't installed correctly.

**Comment by netj** [comment]
I may have forgotten `make` became a runtime dependency. Will push a fix fairly soon. Thanks for reporting!
