### ISSUE TITLE
Installation error with pbzip2

### ISSUE THREAD

**Issue by xiaoling** [HazyResearch/deepdive#519]
A fresh clone of deepdive on Ubuntu 15.04.. Running `make` gave me the following error:
```
# Bundled dependencies: preparing dependency pbzip2
# Building dependency pbzip2 (c3ff1ac6c7319a72e731ade9b2034f5a4be6ac5c)
make[1]: Entering directory '/opt/deepdive/extern/.build/bundled.prep/pbzip2/pbzip2-1.1.13'
g++ -O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_STACKSIZE_CUSTOMIZATION -pthread -D_POSIX_PTHREAD_SEMANTICS  pbzip2.cpp BZ2StreamScanner.cpp ErrorContext.cpp -o pbzip2 -lbz2 -lpthread
pbzip2.cpp:33:19: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
                   ^
compilation terminated.
Makefile:70: recipe for target 'pbzip2' failed
make[1]: *** [pbzip2] Error 1
make[1]: Leaving directory '/opt/xiao/deepdive/extern/.build/bundled.prep/pbzip2/pbzip2-1.1.13'
```

`make depends` might fix this but I don't have sudo privileges on this machine.

Solution: I manually downloaded bzip2-1.0.6.tar.gz and built it in the unpacked folder. Then I copied two files `libbz2.a` and `bzlib.h` to the `/opt/deepdive/extern/.build/bundled.prep/pbzip2/pbzip2-1.1.13` folder. Finally I ran `make pbzip2-static` in the `pbzip2-1.1.13` folder and continued `make` in the deepdive folder.

Hope it helps. -Xiao

**Comment by netj** [comment]
Thanks for your input @xiaoling.  This has been already added as [a build dependency in the installers](https://github.com/HazyResearch/deepdive/blob/05bde411b07e1496a1d4c78c9a7c67ef59ace499/util/install/install.Ubuntu.sh#L25).  Maybe it's time to ask your admin for a:
```bash
sudo bash <(curl -fsSL git.io/getdeepdive) _deepdive_build_deps
```

**Comment by chenliangfei** [comment]
[root@localhost pbzip2-1.1.13]# make
g++ -O2 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DUSE_STACKSIZE_CUSTOMIZATION -pthread -D_POSIX_PTHREAD_SEMANTICS  pbzip2.cpp BZ2StreamScanner.cpp ErrorContext.cpp -o pbzip2 -lbz2 -lpthread
pbzip2.cpp:33:19: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
                   ^
compilation terminated.
Makefile:70: recipe for target 'pbzip2' failed
make: *** [pbzip2] Error 1
[root@localhost pbzip2-1.1.13]#

**Comment by chenliangfei** [comment]
How to solve this problem?
