### ISSUE TITLE
Custom Annotations

### ISSUE THREAD

**Issue by naddou14** [HazyResearch/deepdive#520]
Hello,

First of all, I want to say thank you to every person who participated in DeepDive's development. It is really great!! 
Second, I want to know if there is any news about custom annotations? If not, can anyone please make the approach that @netj has proposed in [Issue 388](https://github.com/HazyResearch/deepdive/issues/388) more clear?

Thank you for answering.
Nadia

**Comment by netj** [comment]
Hi @naddou14, not exactly sure what you mean by custom annotations, but you can think of most pieces DeepDive offer for data processing and statistical inference at the mention level as doing the "custom annotations" over the corpus.  We use different terms like "mention level extraction" or "candidate mapping" but they can be viewed as the same things.  The [spouse example](http://deepdive.stanford.edu/example-spouse) used in our tutorial is basically decorating the corpus with a custom "mention of spouse relationship" annotations.

**Comment by naddou14** [comment]
I'm trying to adapt DeepDive to my needs so I have to extract first of all "Vehicles" mentions for example (like you have done in spouse example to extract "person" mentions). I succeeded in adding Vehicles mentions extraction apart with CoreNLP but not in DeepDive. And now I want to do so with DeepDive. Can you advise me please?

Thank you

**Comment by netj** [comment]
If those are output as extra NER tags, you'll be able to access them from DeepDive.  Spouse example shows how to run CoreNLP through Bazaar/Parser and use the PERSON NER tag to map candidates. It sounds like you can just plug them into DeepDive?

**Comment by naddou14** [comment]
Finally i added my regular expressions in a file and i added the "regexner" option in the parser and now it works fine. Thank your for your answers

**Comment by JBKBO** [comment]
@naddou14 can you please give some more hints where exactly one has to put the file? 
Im want to replace the NER model with my own model but have no clue where to do it.

**Comment by naddou14** [comment]
Hi @JBKBO,

With pleasure :) 
So you have to modify the file "yourproject"\udf\bazaar\parser\src\main\scala\com\clearcut\nlp\Main.scala by adding:
-> annotators: String = "tokenize, cleanxml, ssplit, pos, lemma, ner, parse, **regexner**" in Config Class
-> **props.put("regexner.mapping", "Path to your regular expressions file")** for me the file was in udf\bazaar\parser\

Then you have to rebuild the scala part by typing "**sbt/sbt compile**" when you are under **udf\bazaar\parser\**

I hope this will help you.
Nadia

**Comment by JewelYueng** [comment]
Hi @naddou14,
I modified the file Main.scala as you said. But there was an error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Provided mapping file is in wrong format. This line is bad:  semiconductor PRODUCT
```

and my file is a txt with the content as follow:

```
semiconductor PRODUCT
```

Did you ever suffer from this error ?
