### ISSUE TITLE
Different result between Mac and Ubuntu

### ISSUE THREAD

**Issue by lanphan** [HazyResearch/deepdive#525]
Hi all,
After running spouse example on 2 different machines, Mac and Ubuntu, I got 2 different results.
Please take a look at my screenshots below:
1/ Ubuntu result
  + Official deepdive version
  + Only run "deepdive do has_spouse" ("deepdive do probabilities" got problem, waiting to fix)
  + DEEPDIVE_NUM_PARALLEL_UNLOADS=3 and DEEPDIVE_NUM_PARALLEL_LOADS=3
<img width="882" alt="ubuntu_result" src="https://cloud.githubusercontent.com/assets/360654/13889272/4224c928-ed78-11e5-856e-84a3fa5532e1.png">

2/ Mac result
  + Patch version (mkmimo.sh script)
  + Run "deepdive do probabilities"
  + DEEPDIVE_NUM_PARALLEL_UNLOADS=1 and DEEPDIVE_NUM_PARALLEL_LOADS=1
<img width="1071" alt="mac_result" src="https://cloud.githubusercontent.com/assets/360654/13889279/4fcdcfde-ed78-11e5-84f1-cec2114e22e0.png">

See that:
  + `articles` and `spouses_dbpedia` table are the same: OK
  + `sentences` tables and all tables afterward are different (result in Mac is larger): **NOT OK**

Maybe bug in mkmimo or parallel load/unload?

**Comment by netj** [comment]
Possibly.  Please try again after installing the latest stable release.  mkmimo has been updated to a version that probably won't crash your Mac any more.

**Comment by lanphan** [comment]
@netj 
Thank Jaeho, I'll test this again with Deepdive 0.8.1.
BTW, is there any process to upgrade Deepdive? Or, I'll install again to make it overwrite?

**Comment by netj** [comment]
In most cases you can just overwrite by running the installer again. However it may be safer to put your old one aside and just repeat the installation.

**Comment by chrismre** [comment]
Any closure here? Can we close this issue? :)

**Comment by lanphan** [comment]
@chrismre 
Not yet tested again, I'll do it soon this week.
However, it seems that new DeepDive got some problems with installation (comment from netza2 in gitter + my error report in #530), would you please take a look at these problems?

**Comment by netj** [comment]
I believe this is no longer an issue since the fix with multithreaded mkmimo.
