### ISSUE TITLE
Error with setup parser of Bazaar

### ISSUE THREAD

**Issue by lanphan** [HazyResearch/deepdive#530]
Hi all,
I try to run example spouse in Docker container:
- install deepdive under non-sudo user: ok
- download spouse example and install open-jdk8: ok
- setup to use jdk8 by default: ok
- got problem with "deepdive do init/app" below (specifically, got problem with running ./setup.sh of Bazaar's parser)

```
[Skipping download: /home/deepdive/spouse_example/udf/bazaar/parser/lib/stanford-srparser-2014-10-23-models.jar already exists
[info] Loading project definition from /home/deepdive/spouse_example/udf/bazaar/parser/project
[info] Set current project to deepdive-nlp-parser (in build file:/home/deepdive/spouse_example/udf/bazaar/parser/)
[info] Compiling 6 Scala sources to /home/deepdive/spouse_example/udf/bazaar/parser/target/scala-2.10/classes...
[error] error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
...
```

From line "[error] error while loading <root>, error in opening zip file", it seems that I got permission related error? Does this mean I need sudo permission to run deepdive?
[error_setup_parser.txt](https://github.com/HazyResearch/deepdive/files/201217/error_setup_parser.txt)

**Comment by netj** [comment]
Not sure about the exact cause, but sometimes scala dependencies can go corrupt or the jar downloads sporadically fail.  Maybe you can retry after removing `~/.ivy2`?  Soon we're going to strip the thick glue code and introduce a more direct way to use CoreNLP.  However, I don't see an obvious reason why this shouldn't work in Docker.

**Comment by netj** [comment]
We will soon merge #566 (a thin wrapper for CoreNLP) and Docker compatibility changes, which will get rid of these issues.
