### ISSUE TITLE
Support for correlations between categorical variables 

### ISSUE THREAD

**Issue by raphaelhoff** [HazyResearch/deepdive#531]
Categorical variables are great for simplifying code and improving efficiency, but there's one limitation: we can't easily express correlations between variables. Factor functions such as `Imply` or `And` only apply to Boolean variables, and the only factor function available for categorical variables, `Multinomial`, generates one weight for each combination of values of the arguments variables. @zifeishan has experimented with switching from Categorical variables back to Booleans in order to take advantage of these richer functions and learn fewer weights, and saw improvements in results.

I see that there's a comment about this problem in the [documentation](http://deepdive.stanford.edu/writing-model-ddlog). Is there a roadmap for the planned changes?

**Comment by chrismre** [comment]
@raphaelhoff Can you leave a few samples of what you'd like to do? In particular, you should be able to filter based on the categorical value.... and what do you mean by correlations between values (They are exclusive...)
@netj @alldefector

**Comment by raphaelhoff** [comment]
Here's what I would like to do. Let's assume we are building a NER tagger that assigns a label to each word in a document.

Our set of labels is `labels = { HOUSE_NUM, STREET, APT, SUITE, ZIP, CITY, ZIP, PO_BOX, STATE, O}` and we create a categorical random variable `v1, v2, v3` for each word. 

A labeled document:
```
O     O     O  CITY       O O   O       O HOUSE_NUM STREET STREET  APT APT CITY       CITY CITY ZIP   O
Peter lives in Washington . His address : 3432      New    Blvd    Apt 3   Washington ,    DC   20001 .
```

1. We would like to learn how likely different mentions of the same word in a document will get the same label, so that the system will make the first mention of Washington a CITY and not a STATE. 
   We add the following ddlog factor:

   ```
   @weight("?")
   Multinomial(tag(word_id_1), tag(word_id_2)) :- ...
   ```

   The problem is that we are now learning 100 weights, ie. for each combination of labels. But actually all other weights are irrelevant to us, we would only like to distinguish two cases:
     a) two mentions of the same word have the same label
     b) two mentions of the same word have different label

2. We would also like to learn that certain label transitions are more likely than others. For example, we might see `HOUSE_NUM STREET STREET` or `HOUSE_NUM STREET APT`, but probably not `HOUSE_NUM ZIP O` or `STREET APT STREET`. Again, there's no need to learn a weight for every combination of labels, since most simply don't make sense.

3. We may want to condition on some words. For example, when seeing "address :", the labels for following tokens may be `HOUSE_NUM STREET` or perhaps `PO_BOX CITY`. Again, we want to rule out impossible combinations, learning only a single weight for all of them combined (or perhaps not letting the sampler consider such combinations at all).

Now, suppose we only had two labels `{ CITY, O }`, then we could use our Boolean factor functions, eg.
`And(..,..)` to achieve some of the above.

**Comment by chrismre** [comment]
- So this is a performance optimization? Is there something semantically wrong with having those weights? Is this in response to a particular performance issue (as it seems the system should just do the right thing here...) 

- If you only wanted to add manual features for equal pairs, then why not write a rule that filters on equality? This should generate weights only for those pairs (that's the meaning of the weight being a function of the supported pairs. We've had this syntax for a while... @netj has this changed? We can discuss on the white board.

Why worry about these impossible combinations instead of learning 0 weights from data--especially since your impossible combinations now have to be enumerated by hand (which seems to defeat the point of learning).

cc: @mikecafarella

**Comment by alldefector** [comment]
The "equal pair" or skip-chain factors are certainly still supported: http://deepdive.stanford.edu/example-chunking#3-statistical-learning-and-inference

I guess "filter based on the categorical value" is not supported yet? @netj

**Comment by raphaelhoff** [comment]
I think the "equal pair" and "filter based on the categorical value" would get us a long way. @alldefector
Can you point me to the "equal pair" factor for Multinomials? @netj Can I do the filtering based on categorical value?

Some more background: My main motivation is to improve quality, though performance may matter. The predicted sequence of labels sometimes "doesn't make sense", so I am thinking that factors over 2, 3, 4 variables (representing adjacent words) may help. 

Here is an example that shows why 3 or 4 variable factors may be useful: Suppose we have the following
label sequence and we are unsure about the ?? label.

```
?? CITY STATE ZIP
?? CITY STATE O
```

In the first case, the `??` label is likely to be `STREET`, not `O`. In the second case, the `??` is likely
to be `O`, but not `STREET`. So, the label on the fourth word helps disambiguate the first.
Why? In the first case, it's more likely that we are seeing a full address, but in the second case
it's more likely we are just seeing a reference to a city in a sentence since there is no `ZIP` code.
I have more such examples, also for `PERSON` name extraction.

Unfortunately, a factor over four variables adds 10,000 weights here, and more if we consider not just
locations.

Most such "wrong" label sequences will never get generated, so their weight will be 0. However, some
of the "wrong" label sequences will be knocked down during learning and will get a negative weight;
with fewer weights, this negative weight would apply to other "wrong" sequences as well, and the
overall quality of the system will likely improve.

**Comment by alldefector** [comment]
@raphaelhoff here is the link again: http://deepdive.stanford.edu/example-chunking#3-statistical-learning-and-inference
"equal pair" means equal words, not equal labels. Equal labels would be learned by DD.

We can discuss quality improvement offline. For performance, it seems to be closely related to the dense / sparse FG representation @netj is working on for dynamic-scope categorical vars. As DD evolves, it's possible that we'll have more and more sophistication in graph representation; e.g., maybe some notion of lazy grounding.
