### ISSUE TITLE
deepdive silently fails with postgres `psql` and greenplum database  

### ISSUE THREAD

**Issue by raphaelhoff** [HazyResearch/deepdive#553]
Suppose you have installed both greenplum and postgres, and are now trying to run the spouse_example on greenplum. If your default `psql` is points to the postgres version (which is usually fine for executing queries), your deepdive program will fail silently on
```
deepdive create table ... like ...
```

The issue is that the command internally executes `psql -c "\d tablename"` and then parses the output, but the output is different for the postgres and greenplum versions.

Maybe deepdive should throw an error message when the `\d` output is not as expected here
https://github.com/HazyResearch/deepdive/blob/master/database/db-driver/greenplum/db-create-table-like#L19

**Comment by alldefector** [comment]
dup of #494... It always comes back...
