### ISSUE TITLE
Bug: Incomplete loading of domains from grounding

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#569]
We have a sparse categorical app where the inference result (`dd_inference_result_variables`) contain probs for cid = 0,1,2,3,... while those probs should have been for cid = 6,44,333,555,...

After some debugging, I found that the broken step appears to be in `--domains <(flatten factorgraph/domains)` of `process/model/learning`.

The domain dump SQL is correct, covering all categorical vars. The dumped binary files (`domains.part-*.bin.bz2`, we have 31 parts) also appear to be correct -- their total byte count matches the expected size (`select sum(8 + 4 + 4 * dd__count) from dd_variables` == `find -L \"$@\" -type f -size +0 -exec pbzip2 -c -d -k {} + | wc --bytes`). However, the var count from `FactorGraph::load_domains` does not match the total var count (150K or so out of 180K or so; and the ratio is different from run to run).

So, it appears that something is wrong with the `flatten` pipe into the sampler...

**Comment by netj** [comment]
See if grounding with the following produces correct result:
```
export DEEPDIVE_NUM_PROCESSES=1
```
You can probably bunzip2 the single domain binary and feed the sampler with the rest of inputs to see if flatten is the culprit or something else.

I'm suspecting the `load_domains` may be terminating earlier..

**Comment by alldefector** [comment]
OK, that's indeed related. Here is what I tried:
```
rm -f run/model/grounding/variable/link/domains.part*
DEEPDIVE_NUM_PROCESSES=XXX deepdive redo process/grounding/variable/link/dump_domains process/grounding/combine_factorgraph process/model/learning
```

I tried different values of XXX. If XXX is 1 or 20, var count from `load_domains` is correct. If XXX is 28 or above, var count from `load_domains` becomes smaller than expected.

If I just run
```
DEEPDIVE_NUM_PROCESSES=30 deepdive redo process/grounding/combine_factorgraph process/model/learning
```
the var count is always correct.

So, something seems fishy with the concurrency control of [`deepdive compute execute`](https://github.com/HazyResearch/deepdive/blob/master/runner/compute-driver/local/compute-execute) or perhaps file flushing in `sampler-dw text2bin domain /dev/stdin >(pbzip2 >domains.part-${DEEPDIVE_CURRENT_PROCESS_INDEX}.bin.bz2)`, or the symlink creation in `combine_factorgraph`... (In other words, `load_domains` tried to read the part files before they are ready.)

**Comment by alldefector** [comment]
In https://github.com/HazyResearch/deepdive/blob/master/runner/compute-driver/local/compute-execute#L106 , maybe that detects only the completion of `sampler-dw text2bin` even if `pbzip2` continues to run?

**Comment by alldefector** [comment]
If I add `sleep 2` at the end of `process/grounding/variable/link/dump_domains/run.sh`, the problem is fixed. I also saw that the mtime of some `run/model/grounding/variable/link/domains*` files is GREATER than when `flatten factorgraph/domains` was executed. Those kind of confirm that `deepdive compute execute` didn't wait for the dump processes to fully finish.

**Comment by alldefector** [comment]
This post suggests that there is no obvious way to wait for the redirection subprocess (`pbzip2`):
http://unix.stackexchange.com/questions/65192/how-to-wait-for-a-subprocess-used-for-i-o-redirection

If we replace
```
sampler-dw text2bin domain /dev/stdin >(pbzip2 >domains.part-${DEEPDIVE_CURRENT_PROCESS_INDEX}.bin.bz2)
```
with
```
sampler-dw text2bin domain /dev/stdin /dev/stdout | pbzip2 >domains.part-${DEEPDIVE_CURRENT_PROCESS_INDEX}.bin.bz2
```
The problem seems to go away (correct var count).

Lesson is that we should avoid using redirection subprocesses in `compute execute` commands.

@netj any potential issue you see with this change?

**Comment by netj** [comment]
Great finding of the bug!  I totally overlooked such concurrency issue.  I agree we should never use process substitution as a data sink.  Other dump processes should also be rewritten to use standard pipes.  I don't think there's any issue.

**Comment by alldefector** [comment]
Great. What's the best way to deal with the existing pipes, such as https://github.com/HazyResearch/deepdive/blob/master/compiler/compile-config/compile-config-2.01-grounding#L598-L604 ?

**Comment by netj** [comment]
Process substitution is quite inevitable when there are more than one output channel.. so maybe we have to live with it in such cases.

I was quickly experimenting with it and it seems my interactive bash actually waits on the delayed subprocess below:
```
seq 100 |
tee >(sleep 2; wc -l >foo) |
sha1sum >bar
```
Not sure why this works (even in `nohup`) but the grounding scripts with dw don't.  Maybe dw or pbzip2 is handling them specially..

But I guess we can just synchronize with files like below which is guaranteed to work.
```
rm -f foo.ok
seq 100 |
tee >(sleep 1; wc -l >foo; :>foo.ok) |
sha1sum >bar
until [[ -e foo.ok ]]; do sleep 0.1; done
```
I can take care of the rest, turning the last line into a separate command, like `wait-on`.

**Comment by zifeishan** [comment]
@alldefector  Great findings. I ran the pipeline end-to-end 10 times with #570 and confirmed that the problem went away.

**Comment by alldefector** [comment]
Just got bitten by this again in the sharding branch... Worked around (https://github.com/HazyResearch/deepdive/pull/592/commits/0a215b9f7c1b73614f2d57c4ca02552d86278149), but still don't have a good solution for cases where both redirection and tee are used.
