### ISSUE TITLE
Build errors on new Mac due to missing .build dir

### ISSUE THREAD

**Issue by raphaelhoff** [HazyResearch/deepdive#574]
`make depends` failed with

```
This program built for i386-apple-darwin11.3.0
+ has gnuplot
## Finished installation for _deepdive_runtime_deps
sha1sum util/install.sh util/install/install.Mac.sh util/install/install.RedHat.sh util/install/install.Ubuntu.pgxl.sh util/install/install.Ubuntu.sh >.build/depends
/bin/sh: .build/depends: No such file or directory
make: *** [.build/depends] Error 1
```

and `make` failed with

```
+ rsync -aH --delete ddlib/ddlib dist/stage/lib/python/
./stage.sh: line 130: install-shared-libraries-required-by: command not found
make: *** [build] Error 127
```

I then installed `brew` and a few packages `brew install coreutils autoconf automake libtool`, and eventually it worked.

Later, I tried container-based install. It initially failed with

```
$ make build--in-container
./DockerBuild/build-in-container
/Users/raphael/repos/deepdive/DockerBuild/util/@sh: line 27: jq: command not found
make: *** [build--in-container] Error 127
```

After running `brew install jq`, both `make build--in-container` and `make test--in-container` worked great.

**Comment by alldefector** [comment]
@raphaelhoff I suppose `git submodule update --init` fixed them all?

**Comment by vpsm** [comment]
@raphaelhoff I see the same issue when I do `make depends`. Do you recall what exactly you had to do to fix the problem? I tried installing the brew packages you indicated but still have the issue.

**Comment by vpsm** [comment]
I tried the following on an Ubuntu machine as well but still get an error

```
git clone https://github.com/HazyResearch/deepdive.git
cd deepdive
git submodule update --init
make depends
```
The error is:
```
sha1sum util/install.sh util/install/install.RedHat.sh util/install/install.Ubuntu.pgxl.sh util/install/install.Ubuntu.sh util/install/install.Mac.sh >.build/depends
/bin/sh: 1: cannot create .build/depends: Directory nonexistent
Makefile:45: recipe for target '.build/depends' failed
make: *** [.build/depends] Error 2
```

**Comment by alldefector** [comment]
@vpsm Sorry about the errors. I was able to reproduce that in a clean repo. If you run `mkdir .build` first before `make depends`, it seems to work. Let me know if it doesn't. We'll fix the Makefile soon. (cc @netj )
