### ISSUE TITLE
Grounding with categorical variables fails due to single quote in comment

### ISSUE THREAD

**Issue by raphaelhoff** [HazyResearch/deepdive#575]
For example, running the chunking example (yes, code is stale) throws

```
2016-08-11 12:28:34.225592 process/grounding/factor/current_and_next_pos/dump/run.sh: line 60: unexpected EOF while looking for matching `''
```

This error is thrown due to a single quote in the comment here ("doesn't") which the grounding compiler doesn't correctly handle: 
https://github.com/HazyResearch/deepdive/blob/88cf9c1c10bcaadf21edbcb1698505001476aa8c/compiler/compile-config/compile-config-2.01-grounding#L532

Removing the single quote makes this step work.

**Comment by alldefector** [comment]
I have never seen this error before and tests run fine. It sounds like a versioning issue with jq or bash in a bad build (like you said, "stale code").

@raphaelhoff  Could you print the relevant lines from "run.sh"? Maybe also edit it to print out versions of jq and bash.

**Comment by netj** [comment]
Seems not an issue in the latest code, so closing. Moreover, we're bundling jq and bash now, which would reduce the likelihood of these issues (7f048e0dfad55a9ee79d7fcb514d206b013da4cd).
