### ISSUE TITLE
stage.sh missing install-shared-libraries-required-by

### ISSUE THREAD

**Issue by zifeishan** [HazyResearch/deepdive#576]
when I was running `make install` after `make build` it promps that `install-shared-libraries-required-by` command not found:
https://github.com/HazyResearch/deepdive/blob/master/stage.sh#L130

**Comment by zifeishan** [comment]
NVM, it turned out that I forgot to initialize the submodules. (have to run `git submodule update --init` before installation)

**Comment by alldefector** [comment]
same problem happens when building from a clean repo.
