### ISSUE TITLE
Build failure - make depends - on Debian 8

### ISSUE THREAD

**Issue by bjonnh** [HazyResearch/deepdive#578]
Running make depends:

W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

**Comment by netj** [comment]
I guess we never actually tried our build on Debian, only testing a built release on it.

DeepDive's installer does a bunch of `add-apt-repository` for Ubuntu-specific APT repos, which may need to be dropped/adapted for Debian.  For now, I'd recommend manually installing the packages listed here: https://github.com/HazyResearch/deepdive/blob/master/util/install/install.Ubuntu.sh
A patch to make the installer more portable would be also very appreciated. (maybe we could add different APT sources depending on `$LSB`)

**Comment by bjonnh** [comment]
On debian sid, there is no need for this PPA as openjdk is already 8.

Good question for jessie.

Also to run tests (postgres spouse_example) I had do add pyhocon (using pip), pbzip2 and moreutils

**Comment by netj** [comment]
Sorry but we do not plan to support Debian for build.  Please use Ubuntu if possible.  Patches to [`util/install/install.Ubuntu.sh`](https://github.com/HazyResearch/deepdive/blob/master/util/install/install.Ubuntu.sh) for Debian are welcome though!
