### ISSUE TITLE
Build error on Debian 8 and Sid

### ISSUE THREAD

**Issue by bjonnh** [HazyResearch/deepdive#579]
+ rsync -aH --delete ddlib/ddlib dist/stage/lib/python/
./stage.sh: line 130: install-shared-libraries-required-by: command not found
Makefile:103: recipe for target 'build' failed
make: *** [build] Error 127

I searched on all debian packages, none can provide this file. Where is that coming from?

**Comment by netj** [comment]
Please retry `make build` after:
```
git submodule update --init
```
We are trying to migrate our runtime dependencies to *conda* lately and some parts of our build have gotten a bit loose.

**Comment by bjonnh** [comment]
Oh I see, I was going to answer saying that using the last buildkit provided that file.

Thanks.
