### ISSUE TITLE
New Census example doesn't compile on Ubuntu.

### ISSUE THREAD

**Issue by minafarid** [HazyResearch/deepdive#582]
I am trying to compile the new census application and I get the error I am attaching. Is there something I am missing?

![screenshot from 2016-08-18 10 57 44](https://cloud.githubusercontent.com/assets/9206118/17778627/b1a7ff04-6532-11e6-98cc-ba349a8e9f02.png)

**Comment by alldefector** [comment]
@minafarid I cannot seem to repro this... Could you run `deepdive version` to check the build date of deepdive and if it's more than a couple of months old, run `git pull; make build; make install` to rebuild? Let me know if the problem persists even after that.

**Comment by minafarid** [comment]
You were right, it was an older version of deepdive (`deepdive version` results shown below).
```
➜  longtail git:(master) deepdive version
deepdive v0.8.0-79-g28a58de (Linux x86_64)
Information on this build of deepdive follows.

  deepdive version: v0.8.0-79-g28a58de
  deepdive Git commit: 28a58de9eaf92ef16c4777b007ef2d16cb7f0548

  Build Date: 2016-04-26T15:21:44+00:00
  Build Host: testing-worker-linux-docker-babe303d-3437-linux-5.prod.travis-ci.org
  Build Operating System: Linux
  Build Machine: x86_64

  Running Operating System: Linux
  Running Machine: x86_64

➜  longtail git:(master) 
```

I tried to install a new version of deepdive but it failed at `stage` after building most modules. 


![screenshot from 2016-08-18 15 12 52](https://cloud.githubusercontent.com/assets/9206118/17787304/8f7ccb8e-6556-11e6-9441-4b8d30ecf898.png)


I also tried to build it in a Docker container, but it gives me the following error:

![screenshot from 2016-08-18 15 13 05](https://cloud.githubusercontent.com/assets/9206118/17787326/a9e73d2e-6556-11e6-873f-19f98d65e35a.png)

Do you have any recommendations, if you ran into this before?

**Comment by alldefector** [comment]
Yeah, we've seen this error a couple of times... Try running `git submodule update --init` after `git pull`.

**Comment by minafarid** [comment]
Issue fixed. Application compiles and runs successfully. Thank you for your help.
