### ISSUE TITLE
Where are feature weights?

### ISSUE THREAD

**Issue by minafarid** [HazyResearch/deepdive#588]
After running inference, I can see the view `dd_graph_weights` that has the description of features and the weight ID `wid`, but which table/view contains the weights themselves, similar to the ones in the census example https://github.com/HazyResearch/deepdive/tree/master/examples/census

```
lt=# \d dd_graph_weights
  View "public.dd_graph_weights"
   Column    |  Type   | Modifiers 
-------------+---------+-----------
 wid         | bigint  | 
 isfixed     | boolean | 
 initvalue   | integer | 
 description | text    | 
```

**Comment by alldefector** [comment]
If you ran `deepdive do all`, there should be a view called `dd_inference_result_weights_mapping`.

**Comment by minafarid** [comment]
Great!! I suggest this becomes a part of `deepdive run`.

**Comment by alldefector** [comment]
@minafarid `deepdive run` is deprecated... https://github.com/HazyResearch/deepdive/issues/563
