### ISSUE TITLE
Introduction and questions

### ISSUE THREAD

**Issue by vpsm** [HazyResearch/deepdive#590]
Hello,

I work at a startup and am looking at models that can efficiently encode expert/domain knowledge in the form of rules in the model directly and found out about DeepDive via Alchemy->Tuffy->DeepDive. I've spent a couple of weeks getting it going and now that I have some idea about how to use it, I have a few questions and would appreciate if I could get some feedback on it.

1. What is the current status of supporting categorical variables? I see that there is an order of magnitude improvement in learning and inference time when I use a categorical variable with a cardinality of ~30 versus using boolean variables. However, I noticed that the chunking example doesn't use categorical anymore and I could not define rules influencing a particular value of the categorical variable or across categorical and boolean variables.

2. If using boolean variables instead of categorical, what is the best way to express mutual exclusion so that the runtime benefit of a categorical variable can still be achieved?

Appreciate any help and look forward to contributing to this awesome project!

**Comment by chrismre** [comment]
I think @alldefector is in charge of this change--and it should be pushed to master soon :) Adding folks in here who can answer the definitive state of the code. Thanks for the kind words!

**Comment by alldefector** [comment]
Hi @vpsm , we've merged the categorical support into master a couple of months ago. The documentation on the DeepDive website is still stale though as we haven't made a new release yet...

In any case, the chunking example is actually categorical. In the current version of DD, here is how you declare a categorical variable:
https://github.com/HazyResearch/deepdive/blob/master/examples/chunking/app.ddlog#L1-L5

The `@key` annotation marks the "possible-world" key, and fields without `@key` are categorical values (i.e., classes). Note that the `@key` columns are NOT a primary key for the `chunk` table in the DB sense.

All those inference rules are categorical:
https://github.com/HazyResearch/deepdive/blob/master/examples/chunking/app.ddlog#L39-L88

Note that we have got rid of the old awkward `Multinomial(...)` syntax. Right now, we only support the AND factor function over categorical vars (`chunk(s, w1, tag1) ^ chunk(s, w2, tag2)` but not say `chunk(s, w1, tag1) => chunk(s, w2, tag2)`), and don't support mixing categorical vars with boolean vars in the inference rule yet. However, we are making changes (e.g., https://github.com/HazyResearch/deepdive/pull/589) to move toward supporting them.

If you'd like to play with the chunking example on a laptop, you may want to run these first:
```
export SUBSAMPLE_NUM_WORDS_TRAIN=2000
export SUBSAMPLE_NUM_WORDS_TEST=2000
```

The bigram and word-embedding factors are particularly dense (7M factors for 4K vars) to demonstrate the ddlog language, and the above commands would scope down the input data to make sure DD doesn't take forever... (we'll make this example snappier by default at some point.)

**Comment by vpsm** [comment]
Thanks @chrismre @alldefector for the quick response.

@alldefector is the following understanding correct?
```
object_cat?(
    @key obj_id text,
    @key cat_type text
).
```
will create a boolean variable for each possible combination of obj_id and cat_type
```
obj_cat?(
    @key obj_id text,
    cat_type text
).
```
will create a categorical variable for each obj_id.

**Comment by alldefector** [comment]
@vpsm yes, exactly! In the first case, you can leave out both `@key`s -- if no field has `@key`, implicitly all fields form the key and it's a boolean var.

**Comment by vpsm** [comment]
Thanks @alldefector 

I'm facing a few issues compiling and getting the master branch to run. Will report further once I sort those issues out in the other threads :).

Thanks.

**Comment by alldefector** [comment]
Hi @vpsm closing this thread for now. If you encounter other issues (compiling or otherwise), feel free to open a new one :)
