### ISSUE TITLE
pv: unrecognized option '--format=%N %t %b %a (%r)'

### ISSUE THREAD

**Issue by alldefector** [HazyResearch/deepdive#593]
Trying to run census example on a clean install on Ubuntu, but got this error in `process/init/relation/adult`:

```
Loading adult from input/adult.csv.sh (csv format)
pv: unrecognized option '--format=%N %t %b %a (%r)'
Try `pv --help' for more information.
```

There seems to be two versions of pv out there -- one supports `--format`, the other doesn't. Isn't `pv` supposed to be bundled? (`deepdive env` then `which pv` points to /usr/bin/pv)

**Comment by netj** [comment]
The bundling of runtime dependencies was left broken since the conda stuff.  Since conda doesn't seem to cover all open source we use for all platforms (osx), let's drop it.  Fixes to all build issues are coming soon.

**Comment by netj** [comment]
We're bundling everything once again by 7f048e0dfad55a9ee79d7fcb514d206b013da4cd, so this should no longer happen.
