### ISSUE TITLE
2 errors running run_deepdive_tests

### ISSUE THREAD

**Issue by profressor** [HazyResearch/deepdive#600]
>  ✗ postgresql chunking example
>    (in test file test/postgresql/chunking_example.bats, line 19)
>      `f1score=$(get_f1score)' failed
>    **processed 5755 tokens with 2995 phrases; found: 2851 phrases; correct: 2297.**
>    accuracy:  87.25%; precision:  80.57%; recall:  76.69%; FB1:  78.58
>                     : precision:   0.00%; recall:   0.00%; FB1:   0.00  4
>                 ADJP: precision:  84.62%; recall:  62.86%; FB1:  72.13  52
>                 ADVP: precision:  62.24%; recall:  51.26%; FB1:  56.22  98
>                 INTJ: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>                  LST: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>                   NP: precision:  74.75%; recall:  71.59%; FB1:  73.13  1473
>                   PP: precision:  89.25%; recall:  89.84%; FB1:  89.54  614
>                  PRT: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>                 SBAR: precision:  88.89%; recall:  51.61%; FB1:  65.31  36
>                   VP: precision:  89.02%; recall:  87.80%; FB1:  88.41  574
>    /tmp/bats.23348.src: Zeile 9: printf: 78.58: Invalid number 
> 
>  ✗ postgresql chunking example reuse weights
>    (in test file test/postgresql/chunking_example.bats, line 40)
>      f1score=$(get_f1score) failed
>    **processed 4805 tokens with 2335 phrases; found: 2252 phrases; correct: 1694.**
>    accuracy:  85.08%; precision:  75.22%; recall:  72.55%; FB1:  73.86
>                     : precision:   0.00%; recall:   0.00%; FB1:   0.00  5
>                 ADJP: precision:  54.55%; recall:  45.00%; FB1:  49.32  33
>                 ADVP: precision:  46.43%; recall:  38.81%; FB1:  42.28  56
>                CONJP: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>                   NP: precision:  69.14%; recall:  66.00%; FB1:  67.54  1199
>                   PP: precision:  89.45%; recall:  88.52%; FB1:  88.98  474
>                  PRT: precision:   0.00%; recall:   0.00%; FB1:   0.00  0
>                 SBAR: precision:  86.36%; recall:  51.35%; FB1:  64.41  22
>                   VP: precision:  81.64%; recall:  84.19%; FB1:  82.89  463
>    /tmp/bats.23348.src: Zeile 9: printf: 73.86: Invalid number

This is what I get running run_deepdive_tests. Any help appreciated.

System: 16.04.1 LTS
DeepDive: 0.8 stable

**Comment by netj** [comment]
It looks like you are running tests under a locale that doesn't treat `.` as the decimal mark.
Please rerun them after:
```
LC_NUMERIC=C
```
We'll fix the tests to be robust from user locale in the future.

See also: http://stackoverflow.com/questions/12845997/unexplicable-error-in-bash-printf-command-inside-a-script-returns-invalid-numb
