### ISSUE TITLE
Trying to change Postgres configuration.

### ISSUE THREAD

**Issue by DarkDataAnalytics** [HazyResearch/deepdive#612]
Hi,
I am running 0.90 from docker on an EC2 instance. This instance R3.4xLarge has a lot of memory ( 122 GB ) and I have the feeling that the bottleneck on my tests ( spouse with a 50k lines subset ) is the access to Postgres. So I am trying to change the configuration of Postgres but I can stop the service. It asks me the password for joyan. Does anyone has it ?

Cheers
Bruno

**Comment by netj** [comment]
Hi Bruno,

If you're using the sandbox, postgres runs in a separate container (`database` service in the [docker-compose.yml](https://github.com/HazyResearch/deepdive/blob/master/sandbox/docker-compose.yml)).  You'd have to either break into that container with `docker exec -it ... bash` after identifying it from `docker ps`, or add some config params you find from https://hub.docker.com/_/postgres/ to the .yml file.

There's no password for the user jovyan (from official jupyter notebook containers), but you can always pretend as root in any container by telling `docker exec --user 0 ...`.
