### ISSUE TITLE
"deepdive corenlp" this command is not in 0.8.x-STABLE version

### ISSUE THREAD

**Issue by EadrenKing** [HazyResearch/deepdive#630]
I followed the tutorial in [spouse example](https://github.com/HazyResearch/deepdive/blob/master/doc/example-spouse.md). when i go to step 1.2, execute "deepdive do sentences", something goes wrong with me. I guess the release version(0.8.x STABLE) doesn't have the "deepdive corenlp" command. How can I go on? Thanks in advance

**Comment by netj** [comment]
Please see the instructions in the latest https://github.com/LatticeData/deepdive/blob/alpha/doc/installation.md to use the latest code.

**Comment by EadrenKing** [comment]
Hi! https://github.com/LatticeData/deepdive/blob/alpha/doc/installation.md is NOT FOUND

**Comment by netj** [comment]
Sorry I meant https://github.com/HazyResearch/deepdive/blob/master/doc/installation.md

**Comment by EadrenKing** [comment]
I used the Quick Installation. On the other hand, I mean I have the same problem as issue #604
