### ISSUE TITLE
plpy

### ISSUE THREAD

**Issue by zhangce** [HazyResearch/deepdive#73]
kbp10docs=# SELECT (__X.__COLUMN).doc_id, (__X.__COLUMN).mention_id, (__X.__COLUMN).sentence_id, (__X.__COLUMN).word, (__X.__COLUMN).type
kbp10docs-# FROM (SELECT func_ext_mention( doc_id, sentence_id, words, pos, ner, lemma, character_offset_begin, character_offset_end ) AS __COLUMN
kbp10docs(# from  sentence) as __X;
ERROR:  length of returned sequence did not match number of columns in row  (seg7 slice1 madmax4.stanford.edu:50007 pid=33719)
DETAIL:  
	 while creating return value
PL/Python function "func_ext_mention"

Does not throw errors now

**Comment by zifeishan** [comment]
This bug is actually a more general non-termination bug when executing SQL queries by a file. Fixed in https://github.com/HazyResearch/deepdive/pull/251.
