### ISSUE TITLE
SQL extractor does not parse whether the input is valid...

### ISSUE THREAD

**Issue by zhangce** [HazyResearch/deepdive#82]
Following one should throw an error, but does not

    ext_el_feature_coref {
      input: """
        INSERT INTO el_features_highprec
      select t0.doc_id, t0.mid1, t1.fid, 'co'::TEXT
      FROM   coref_candidates t0, el_features_highprec t1 
      WHERE  t1.feature= 'es' AND t0.mid2 = t1.mention_id;
    """
    dependencies : ["ext_coref_candidate", "ext_el_feature_extstr_person"]
      style: "sql_extractor"
    }

**Comment by netj** [comment]
Probably fixed by #251 which adds a flag `psql -v ON_ERROR_STOP=1` to stop on error.
